name: aap
channels: [conda-forge]
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scipy
  - matplotlib
  - scikit-learn
  - statsmodels
  - jax
  - jupyter
  - nbformat
  - ipykernel
  - jupyter-cache
  - pyyaml
