<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>6&nbsp; Complejidad, sesgo y varianza – Aprendizaje Automático: Predicción</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../capitulos/07-regularizacion.html" rel="next">
<link href="../capitulos/05-preparacion-datos.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ce76667f72787a46eecac846ed35d09d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-dee1b86ca0bbb38d562930b9728b1e11.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../assets/styles.css">
</head>

<body class="nav-sidebar floating slimcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../capitulos/06-complejidad.html">Complejidad y generalización</a></li><li class="breadcrumb-item"><a href="../capitulos/06-complejidad.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Complejidad, sesgo y varianza</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="../index.html" class="sidebar-logo-link">
      <img src="../assets/img/cunef-logo.png" alt="CUNEF Universidad" class="sidebar-logo light-content py-0 d-lg-inline d-none">
      <img src="../assets/img/cunef-logo.png" alt="CUNEF Universidad" class="sidebar-logo dark-content py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Aprendizaje Automático: Predicción</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Presentación de la asignatura</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Fundamentos del aprendizaje predictivo</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/01-senal-ruido.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Datos = señal + ruido</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/02-aprender-minimizando.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Aprender minimizando</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/03-modelos-lineales.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Modelos lineales con muchas variables</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Evaluación y datos</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/04-evaluacion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Evaluar para generalizar</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/05-preparacion-datos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Preparar datos sin contaminar la evaluación</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Complejidad y generalización</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/06-complejidad.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Complejidad, sesgo y varianza</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/07-regularizacion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Regularización</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/08-seleccion-dimension.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Selección de variables y reducción de dimensión</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Otros métodos</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../capitulos/09-arboles.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Árboles de regresión</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Hojas de problemas</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../problemas/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Hojas de problemas</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../problemas/hoja-01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Hoja 1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../problemas/hoja-02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Hoja 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../problemas/hoja-03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Hoja 3</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../problemas/hoja-04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Hoja 4</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../problemas/hoja-05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Hoja 5</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../problemas/hoja-06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Hoja 6</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../problemas/hoja-07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Hoja 7</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../problemas/hoja-08.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Hoja 8</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../problemas/hoja-09.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Hoja 9</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Apéndices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../curso/guia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Guía de la asignatura</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../curso/calendario.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Calendario</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../curso/evaluacion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Evaluación</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../curso/politica-ia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Política de uso de IA generativa</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../curso/proyecto.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">El proyecto: un flujo completo de predicción</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../curso/algebra.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Cálculo y álgebra que vas a necesitar</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../curso/probabilidad.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Repaso de probabilidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../curso/indice-resultados.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Índice de resultados</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../curso/glosario.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Glosario y notación</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../curso/trazabilidad.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Trazabilidad con la guía docente</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenidos</h2>
   
  <ul>
  <li><a href="#la-representación-decide-qué-se-puede-aprender" id="toc-la-representación-decide-qué-se-puede-aprender" class="nav-link active" data-scroll-target="#la-representación-decide-qué-se-puede-aprender">La representación decide qué se puede aprender</a></li>
  <li><a href="#características-polinómicas-e-interacciones" id="toc-características-polinómicas-e-interacciones" class="nav-link" data-scroll-target="#características-polinómicas-e-interacciones">Características polinómicas e interacciones</a></li>
  <li><a href="#un-algoritmo-produce-modelos-distintos-con-muestras-distintas" id="toc-un-algoritmo-produce-modelos-distintos-con-muestras-distintas" class="nav-link" data-scroll-target="#un-algoritmo-produce-modelos-distintos-con-muestras-distintas">Un algoritmo produce modelos distintos con muestras distintas</a></li>
  <li><a href="#la-descomposición-sesgo-varianza" id="toc-la-descomposición-sesgo-varianza" class="nav-link" data-scroll-target="#la-descomposición-sesgo-varianza">La descomposición sesgo-varianza</a></li>
  <li><a href="#la-curva-en-u-y-lo-que-la-validación-cruzada-logra-ver" id="toc-la-curva-en-u-y-lo-que-la-validación-cruzada-logra-ver" class="nav-link" data-scroll-target="#la-curva-en-u-y-lo-que-la-validación-cruzada-logra-ver">La curva en U y lo que la validación cruzada logra ver</a></li>
  <li><a href="#caso-práctico-la-curva-en-u-en-los-datos-de-madrid" id="toc-caso-práctico-la-curva-en-u-en-los-datos-de-madrid" class="nav-link" data-scroll-target="#caso-práctico-la-curva-en-u-en-los-datos-de-madrid">Caso práctico: la curva en U en los datos de Madrid</a></li>
  <li><a href="#ejercicios" id="toc-ejercicios" class="nav-link" data-scroll-target="#ejercicios">Ejercicios</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../capitulos/06-complejidad.html">Complejidad y generalización</a></li><li class="breadcrumb-item"><a href="../capitulos/06-complejidad.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Complejidad, sesgo y varianza</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Complejidad, sesgo y varianza</span></h1>
<p class="subtitle lead">Aprender curvas y entender lo que cuestan</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="la-representación-decide-qué-se-puede-aprender" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="la-representación-decide-qué-se-puede-aprender">La representación decide qué se puede aprender</h2>
<p>El capítulo anterior terminó con un diagnóstico: la clase de hipótesis considerada hasta ahora (funciones lineales) puede ser insuficiente.</p>
<p>Conviene ver primero qué tiene de limitante esa suposición. Para ello, simularemos una señal <strong>deliberadamente</strong> no lineal.</p>
<div id="6b32abea" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> matplotlib <span class="im">import</span> pyplot <span class="im">as</span> plt</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>torch.set_default_dtype(torch.float64)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>AZUL, GRIS, NARANJA, TINTA <span class="op">=</span> <span class="st">"#151f6c"</span>, <span class="st">"#8b8e95"</span>, <span class="st">"#ff5700"</span>, <span class="st">"#1b1d21"</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>NOISE <span class="op">=</span> <span class="fl">0.2</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>REPETICIONES <span class="op">=</span> <span class="dv">2000</span>      </span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>rejilla <span class="op">=</span> torch.linspace(<span class="dv">0</span>, <span class="dv">2</span>, <span class="dv">400</span>)                         </span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> senal(x):</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> torch.sin(torch.pi <span class="op">*</span> x)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> genera(n, semilla):</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>    torch.manual_seed(semilla)</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>    x <span class="op">=</span> torch.rand(n) <span class="op">*</span> <span class="dv">2</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> x, senal(x) <span class="op">+</span> NOISE <span class="op">*</span> torch.randn(n)</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>x, y <span class="op">=</span> genera(<span class="dv">36</span>, semilla<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="bu">len</span>(x)<span class="sc">}</span><span class="ss"> observaciones, entrada en [0, 2], ruido de nivel </span><span class="sc">{</span>NOISE<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"suelo de ruido: sigma^2 = </span><span class="sc">{</span>NOISE <span class="op">**</span> <span class="dv">2</span><span class="sc">:.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>36 observaciones, entrada en [0, 2], ruido de nivel 0.2
suelo de ruido: sigma^2 = 0.0400</code></pre>
</div>
</div>
<p>La señal es <span class="math inline">\(f(x)=\sin(\pi x)\)</span> sobre <span class="math inline">\([0,2]\)</span>. El ruido es gaussiano de nivel <span class="math inline">\(\sigma=0.2\)</span>, de modo que ningún modelo puede tener un riesgo menor que <span class="math inline">\(\sigma^2=0.04\)</span>.</p>
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="fl">6.0</span>, <span class="fl">3.2</span>))</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>ax.plot(rejilla, senal(rejilla), color<span class="op">=</span>TINTA, lw<span class="op">=</span><span class="fl">1.8</span>, label<span class="op">=</span><span class="st">"señal"</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>ax.scatter(x.numpy(), y.numpy(), s<span class="op">=</span><span class="dv">18</span>, color<span class="op">=</span>GRIS, alpha<span class="op">=</span><span class="fl">0.75</span>, zorder<span class="op">=</span><span class="dv">3</span>,</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>           label<span class="op">=</span><span class="st">"las 36 observaciones"</span>)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>ax.<span class="bu">set</span>(xlabel<span class="op">=</span><span class="st">"$x$"</span>, ylabel<span class="op">=</span><span class="st">"$y$"</span>)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>ax.legend(fontsize<span class="op">=</span><span class="fl">8.5</span>, loc<span class="op">=</span><span class="st">"lower left"</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="fig-senal-cruda" class="quarto-float quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<div aria-describedby="fig-senal-cruda-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div id="6803d185" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="06-complejidad_files/figure-html/cell-4-output-1.png" class="figure-img" width="768" height="403"></p>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-margin quarto-float-caption quarto-float-fig margin-caption" id="fig-senal-cruda-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.1: Las treinta y seis observaciones y la señal que las genera. La señal sube en la primera mitad del recorrido y baja en la segunda, así que ninguna recta puede seguirla: lo que una recta gane en un tramo lo pierde en el otro.
</figcaption>
</figure>
</div>
<p>Ahora ajustemos una recta, y veamos qué sucede. Utilizaremos un tamaño muestral creciente. Nótese que, al conocer la señal real, podemos calcular estimar el riesgo verdadero.</p>
<div id="baae742c" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="annotated-cell-2"><pre class="sourceCode python code-annotation-code code-with-copy code-annotated"><code class="sourceCode python"><span id="annotated-cell-2-1"><a href="#annotated-cell-2-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> ajusta_recta(x, y):</span>
<span id="annotated-cell-2-2"><a href="#annotated-cell-2-2" aria-hidden="true" tabindex="-1"></a>    X <span class="op">=</span> torch.stack([torch.ones(<span class="bu">len</span>(x)), x], dim<span class="op">=</span><span class="dv">1</span>)</span>
<span id="annotated-cell-2-3"><a href="#annotated-cell-2-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> torch.linalg.lstsq(X, y).solution</span>
<span id="annotated-cell-2-4"><a href="#annotated-cell-2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-2-5"><a href="#annotated-cell-2-5" aria-hidden="true" tabindex="-1"></a></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-2" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-2-6" class="code-annotation-target"><a href="#annotated-cell-2-6" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> riesgo_verdadero_recta(w, resolucion<span class="op">=</span><span class="dv">2000</span>):</span>
<span id="annotated-cell-2-7"><a href="#annotated-cell-2-7" aria-hidden="true" tabindex="-1"></a>    rejilla <span class="op">=</span> torch.linspace(<span class="dv">0</span>, <span class="dv">2</span>, resolucion)</span>
<span id="annotated-cell-2-8"><a href="#annotated-cell-2-8" aria-hidden="true" tabindex="-1"></a>    prediccion <span class="op">=</span> w[<span class="dv">0</span>] <span class="op">+</span> w[<span class="dv">1</span>] <span class="op">*</span> rejilla</span>
<span id="annotated-cell-2-9"><a href="#annotated-cell-2-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> ((prediccion <span class="op">-</span> senal(rejilla)) <span class="op">**</span> <span class="dv">2</span>).mean().item() <span class="op">+</span> NOISE <span class="op">**</span> <span class="dv">2</span></span>
<span id="annotated-cell-2-10"><a href="#annotated-cell-2-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-2-11"><a href="#annotated-cell-2-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-2-12"><a href="#annotated-cell-2-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> n <span class="kw">in</span> (<span class="dv">30</span>, <span class="dv">300</span>, <span class="dv">3000</span>, <span class="dv">30000</span>):</span>
<span id="annotated-cell-2-13"><a href="#annotated-cell-2-13" aria-hidden="true" tabindex="-1"></a>    w <span class="op">=</span> ajusta_recta(<span class="op">*</span>genera(n, semilla<span class="op">=</span><span class="dv">42</span>))</span>
<span id="annotated-cell-2-14"><a href="#annotated-cell-2-14" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"n = </span><span class="sc">{</span>n<span class="sc">:6d}</span><span class="ss">   riesgo verdadero de la recta ajustada: "</span></span>
<span id="annotated-cell-2-15"><a href="#annotated-cell-2-15" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"</span><span class="sc">{</span>riesgo_verdadero_recta(w)<span class="sc">:.4f}</span><span class="ss">"</span>)</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-2" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-2" data-code-lines="6" data-code-annotation="1">Como conocemos la señal, podemos calcular el riesgo verdadero sin muestrear.</span>
</dd>
</dl>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>n =     30   riesgo verdadero de la recta ajustada: 0.2809
n =    300   riesgo verdadero de la recta ajustada: 0.2377
n =   3000   riesgo verdadero de la recta ajustada: 0.2366
n =  30000   riesgo verdadero de la recta ajustada: 0.2364</code></pre>
</div>
</div>
<p>El riesgo baja de <span class="math inline">\(0.2809\)</span> a <span class="math inline">\(0.2364\)</span> y ahí se queda. Aumentar el tamaño del conjunto de entrenamiento no es capaz de reducir este riesgo.</p>
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="fl">3.0</span>), sharey<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> panel, n <span class="kw">in</span> <span class="bu">enumerate</span>([<span class="dv">30</span>, <span class="dv">3000</span>]):</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    xn, yn <span class="op">=</span> genera(n, semilla<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    w <span class="op">=</span> ajusta_recta(xn, yn)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    ax[panel].scatter(xn.numpy(), yn.numpy(), s<span class="op">=</span><span class="dv">8</span>, color<span class="op">=</span>GRIS, alpha<span class="op">=</span><span class="fl">0.35</span>,</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>                      zorder<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    ax[panel].plot(rejilla, senal(rejilla), color<span class="op">=</span>TINTA, lw<span class="op">=</span><span class="fl">1.8</span>,</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>                   label<span class="op">=</span><span class="st">"señal"</span>)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>    ax[panel].plot(rejilla, w[<span class="dv">0</span>] <span class="op">+</span> w[<span class="dv">1</span>] <span class="op">*</span> rejilla, color<span class="op">=</span>NARANJA, lw<span class="op">=</span><span class="fl">1.8</span>,</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>                   label<span class="op">=</span><span class="st">"recta ajustada"</span>)</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>    ax[panel].<span class="bu">set</span>(xlabel<span class="op">=</span><span class="st">"$x$"</span>, title<span class="op">=</span><span class="ss">f"n = </span><span class="sc">{</span>n<span class="sc">}</span><span class="ss">, riesgo "</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>                                      <span class="ss">f"</span><span class="sc">{</span>riesgo_verdadero_recta(w)<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].<span class="bu">set</span>(ylabel<span class="op">=</span><span class="st">"$y$"</span>)</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].legend(fontsize<span class="op">=</span><span class="fl">8.5</span>, loc<span class="op">=</span><span class="st">"lower left"</span>)</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="fig-recta-insuficiente" class="quarto-float quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<div aria-describedby="fig-recta-insuficiente-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div id="2b21011b" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="06-complejidad_files/figure-html/cell-6-output-1.png" class="figure-img" width="1028" height="377"></p>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-margin quarto-float-caption quarto-float-fig margin-caption" id="fig-recta-insuficiente-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.2: La recta ajustada con treinta observaciones y con cien veces más.
</figcaption>
</figure>
</div>
<p>Lo que necesitamos para reducir este riesgo es una clase de hipótesis que contenga funciones no lineales. Hay una forma de conseguirla esto sin abandonar nada de lo que sabemos.</p>
<div id="def-mapa-caracteristicas" class="theorem definition">
<p><span class="theorem-title"><strong>Definición 6.1 (Mapa de características)</strong></span> Un <strong>mapa de características</strong> es una función <span class="math inline">\(\boldsymbol{\varphi}:\mathbb{R}^{p}\to\mathbb{R}^{d}\)</span> que transforma el vector de variables predictoras en un vector de <span class="math inline">\(d\)</span> <strong>características</strong> <span class="math inline">\(\boldsymbol{\varphi}(\mathbf{x})=\bigl(\varphi_1(\mathbf{x}),\ldots,\varphi_{d}(\mathbf{x})\bigr)^{\mathsf{T}}\)</span>. El modelo asociado es</p>
<p><span id="eq-modelo-caracteristicas"><span class="math display">\[
f_{\boldsymbol{w}}(\mathbf{x})=\boldsymbol{w}^{\mathsf{T}}\boldsymbol{\varphi}(\mathbf{x})=\sum_{j=1}^{d}w_j\,\varphi_j(\mathbf{x}),
\tag{6.1}\]</span></span></p>
<p>y la <strong>matriz de características</strong> <span class="math inline">\(\boldsymbol{\Phi}\in\mathbb{R}^{n\times d}\)</span> tiene por fila <span class="math inline">\(i\)</span> el vector <span class="math inline">\(\boldsymbol{\varphi}(\mathbf{x}_i)^{\mathsf{T}}\)</span>.</p>
</div>
<p>Considerando este mapa de características, el modelo generador completo es el gaussiano de <a href="01-senal-ruido.html#def-modelo-gaussiano" class="quarto-xref">Definición&nbsp;<span>1.4</span></a>, con <a href="#eq-modelo-caracteristicas" class="quarto-xref">Ecuación&nbsp;<span>6.1</span></a> en el lugar de la señal,</p>
<p><span id="eq-gaussiano-caracteristicas"><span class="math display">\[
y_i\,\vert\,\mathbf{x}_i\sim\mathcal{N}\bigl(\boldsymbol{w}^{\mathsf{T}}\boldsymbol{\varphi}(\mathbf{x}_i),\sigma^2\bigr),
\tag{6.2}\]</span></span></p>
<p>que es el modelo lineal-gaussiano de <a href="01-senal-ruido.html#def-lineal-gaussiano" class="quarto-xref">Definición&nbsp;<span>1.6</span></a> con <span class="math inline">\(\boldsymbol{\varphi}(\mathbf{x}_i)\)</span> en lugar de <span class="math inline">\(\mathbf{x}_i\)</span>. <a href="02-aprender-minimizando.html#cor-mle-minimos-cuadrados" class="quarto-xref">Corolario&nbsp;<span>2.1</span></a> sigue aplicando, y ajustar por máxima verosimilitud sigue siendo minimizar el riesgo cuadrático.</p>
<p>Es importante señalar que la expresión de <a href="#eq-modelo-caracteristicas" class="quarto-xref">Ecuación&nbsp;<span>6.1</span></a> es <strong>no lineal en la entrada</strong> pero <strong>lineal en los parámetros</strong>, esto garantiza lo siguiente.</p>
<div id="prp-todo-sirve" class="theorem proposition">
<p><span class="theorem-title"><strong>Proposición 6.1 (Lo visto en el capítulo 3 sigue aplicando)</strong></span> El problema de minimizar el riesgo cuadrático empírico sobre el modelo <a href="#eq-modelo-caracteristicas" class="quarto-xref">Ecuación&nbsp;<span>6.1</span></a> sobre <span class="math inline">\(\boldsymbol{w}\)</span> es el mismo problema del capítulo 3 con <span class="math inline">\(\boldsymbol{\Phi}\)</span> en lugar de <span class="math inline">\(\mathbf{X}\)</span>. En particular, el gradiente es <span class="math inline">\(\frac{2}{n}\boldsymbol{\Phi}^{\mathsf{T}}(\boldsymbol{\Phi}\boldsymbol{w}-\mathbf{y})\)</span>, las ecuaciones normales son <span class="math inline">\(\boldsymbol{\Phi}^{\mathsf{T}}\boldsymbol{\Phi}\boldsymbol{w}=\boldsymbol{\Phi}^{\mathsf{T}}\mathbf{y}\)</span>, y el ajuste es único si <span class="math inline">\(\boldsymbol{\Phi}\)</span> tiene rango completo por columnas.</p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Demostración</em>. </span>El riesgo empírico es <span class="math inline">\(\hat{R}(\boldsymbol{w})=\frac{1}{n}\left\lVert \mathbf{y}-\boldsymbol{\Phi}\boldsymbol{w} \right\rVert^2\)</span>, que es literalmente la expresión de <a href="03-modelos-lineales.html#prp-riesgo-matricial" class="quarto-xref">Proposición&nbsp;<span>3.1</span></a> con <span class="math inline">\(\boldsymbol{\Phi}\)</span> en el lugar de <span class="math inline">\(\mathbf{X}\)</span>. Ninguna de las demostraciones del capítulo 3 usa de dónde salen las columnas de la matriz, solo que sean números fijos dada la muestra, y las características lo son porque <span class="math inline">\(\boldsymbol{\varphi}\)</span> no depende de <span class="math inline">\(\boldsymbol{w}\)</span>. Por tanto se aplican sin cambios <a href="03-modelos-lineales.html#thm-gradiente-vectorial" class="quarto-xref">Teorema&nbsp;<span>3.1</span></a> y <a href="03-modelos-lineales.html#thm-existencia-unicidad" class="quarto-xref">Teorema&nbsp;<span>3.2</span></a>.</p>
</div>
<p>La consecuencia práctica es que ajustar este nuevo modelo no cuesta ni un algoritmo nuevo ni una teoría nueva: simplemente tenemos que construir la nueva matriz de características.</p>
<p>Comencemos por entender un caso sencillo. Si contamos con una única variable predictora, podemos construir un mapa de características tomando sus potencias hasta un grado <span class="math inline">\(d\)</span>,</p>
<p><span id="eq-caracteristicas-polinomicas"><span class="math display">\[
\boldsymbol{\varphi}(x)=(1,x,x^2,\ldots,x^{d})^{\mathsf{T}},
\tag{6.3}\]</span></span></p>
<p>de modo que la fila <span class="math inline">\(i\)</span> de <span class="math inline">\(\boldsymbol{\Phi}\)</span> es <span class="math inline">\((1,x_i,x_i^2,\ldots,x_i^{d})\)</span> y el modelo de <a href="#eq-modelo-caracteristicas" class="quarto-xref">Ecuación&nbsp;<span>6.1</span></a> es el polinomio</p>
<p><span class="math display">\[
f_{\boldsymbol{w}}(x)=w_0+w_1x+w_2x^2+\cdots+w_dx^{d}.
\]</span></p>
<p>Qué grado <span class="math inline">\(d\)</span> elegir es el asunto que discute este capítulo. Probemos con tres valores diferentes y observemos qué sucede.</p>
<div id="cb1a5205" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> caracteristicas(x, grado):</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> torch.stack([x <span class="op">**</span> j <span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(grado <span class="op">+</span> <span class="dv">1</span>)], dim<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> ajusta(x, y, grado):</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> torch.linalg.lstsq(caracteristicas(x, grado), y).solution</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> riesgo_verdadero(w, grado, resolucion<span class="op">=</span><span class="dv">2000</span>):</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>    rejilla <span class="op">=</span> torch.linspace(<span class="dv">0</span>, <span class="dv">2</span>, resolucion)</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>    prediccion <span class="op">=</span> caracteristicas(rejilla, grado) <span class="op">@</span> w</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> ((prediccion <span class="op">-</span> senal(rejilla)) <span class="op">**</span> <span class="dv">2</span>).mean().item() <span class="op">+</span> NOISE <span class="op">**</span> <span class="dv">2</span></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'grado'</span><span class="sc">:&gt;6}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'parámetros'</span><span class="sc">:&gt;11}</span><span class="ss"> "</span></span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="sc">{</span><span class="st">'riesgo en train'</span><span class="sc">:&gt;16}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'riesgo verdadero'</span><span class="sc">:&gt;17}</span><span class="ss">"</span>)</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> grado <span class="kw">in</span> (<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">9</span>):</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>    w <span class="op">=</span> ajusta(x, y, grado)</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>    en_train <span class="op">=</span> ((caracteristicas(x, grado) <span class="op">@</span> w <span class="op">-</span> y) <span class="op">**</span> <span class="dv">2</span>).mean().item()</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>grado<span class="sc">:6d}</span><span class="ss"> </span><span class="sc">{</span>grado <span class="op">+</span> <span class="dv">1</span><span class="sc">:11d}</span><span class="ss"> </span><span class="sc">{</span>en_train<span class="sc">:16.4f}</span><span class="ss"> "</span></span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"</span><span class="sc">{</span>riesgo_verdadero(w, grado)<span class="sc">:17.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> grado  parámetros  riesgo en train  riesgo verdadero
     1           2           0.1538            0.2384
     3           4           0.0217            0.0546
     9          10           0.0146            0.0793</code></pre>
</div>
</div>
<p>Como podemos observar, el riesgo en train baja siempre al añadir grado. No obstante, el riesgo verdadero no: baja de <span class="math inline">\(0.2384\)</span> a <span class="math inline">\(0.0546\)</span> y vuelve a subir a <span class="math inline">\(0.0793\)</span>. El modelo de grado 1 no es suficientemente <strong>expresivo</strong> mientras que el modelo de grado 9 está <strong>sobreajustado</strong> (recuerda la <a href="01-senal-ruido.html#def-sobreajuste" class="quarto-xref">Definición&nbsp;<span>1.2</span></a>). El resto de este capítulo trata de arrojar luz sobre estos conceptos.</p>
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">3</span>, figsize<span class="op">=</span>(<span class="dv">9</span>, <span class="fl">2.8</span>), sharey<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> panel, grado <span class="kw">in</span> <span class="bu">enumerate</span>([<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">9</span>]):</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    w <span class="op">=</span> ajusta(x, y, grado)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    ax[panel].scatter(x.numpy(), y.numpy(), s<span class="op">=</span><span class="dv">14</span>, color<span class="op">=</span>GRIS, alpha<span class="op">=</span><span class="fl">0.6</span>,</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>                      zorder<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    ax[panel].plot(rejilla, senal(rejilla), color<span class="op">=</span>TINTA, lw<span class="op">=</span><span class="fl">1.5</span>,</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>                   label<span class="op">=</span><span class="st">"señal"</span>)</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>    ax[panel].plot(rejilla, caracteristicas(rejilla, grado) <span class="op">@</span> w,</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>                   color<span class="op">=</span>NARANJA, lw<span class="op">=</span><span class="fl">1.8</span>, zorder<span class="op">=</span><span class="dv">3</span>, label<span class="op">=</span><span class="st">"ajuste"</span>)</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>    ax[panel].<span class="bu">set</span>(xlabel<span class="op">=</span><span class="st">"$x$"</span>, ylim<span class="op">=</span>(<span class="op">-</span><span class="fl">1.8</span>, <span class="fl">1.8</span>),</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>                  title<span class="op">=</span><span class="ss">f"grado </span><span class="sc">{</span>grado<span class="sc">}</span><span class="ss">, riesgo "</span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>                        <span class="ss">f"</span><span class="sc">{</span>riesgo_verdadero(w, grado)<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].<span class="bu">set</span>(ylabel<span class="op">=</span><span class="st">"$y$"</span>)</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].legend(fontsize<span class="op">=</span><span class="fl">8.5</span>, loc<span class="op">=</span><span class="st">"lower left"</span>)</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="fig-tres-grados" class="quarto-float quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<div aria-describedby="fig-tres-grados-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div id="2c81cf7a" class="cell" data-execution_count="7">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="06-complejidad_files/figure-html/cell-8-output-1.png" class="figure-img" width="1144" height="351"></p>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-margin quarto-float-caption quarto-float-fig margin-caption" id="fig-tres-grados-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.3: Los tres ajustes de la tabla sobre las mismas treinta y seis observaciones. La recta no llega a curvarse; el grado 3 sigue aproximadamente la señal; el grado 9 pasa más cerca de los puntos y por eso baja el riesgo en train.
</figcaption>
</figure>
</div>
</section>
<section id="características-polinómicas-e-interacciones" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="características-polinómicas-e-interacciones">Características polinómicas e interacciones</h2>
<p>Con una sola variable predictora, las características polinómicas son las potencias. Con <span class="math inline">\(p\)</span> variables hay que decidir además qué productos entre ellas se incluyen.</p>
<div id="0846c1e2" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="annotated-cell-4"><pre class="sourceCode python code-annotation-code code-with-copy code-annotated"><code class="sourceCode python"><span id="annotated-cell-4-1"><a href="#annotated-cell-4-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> math <span class="im">import</span> comb</span>
<span id="annotated-cell-4-2"><a href="#annotated-cell-4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-4-3"><a href="#annotated-cell-4-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'variables'</span><span class="sc">:&gt;10}</span><span class="ss"> "</span></span>
<span id="annotated-cell-4-4"><a href="#annotated-cell-4-4" aria-hidden="true" tabindex="-1"></a>      <span class="op">+</span> <span class="st">" "</span>.join(<span class="ss">f"</span><span class="sc">{</span><span class="st">'grado '</span> <span class="op">+</span> <span class="bu">str</span>(g)<span class="sc">:&gt;10}</span><span class="ss">"</span> <span class="cf">for</span> g <span class="kw">in</span> (<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">5</span>)))</span>
<span id="annotated-cell-4-5"><a href="#annotated-cell-4-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> nfeat <span class="kw">in</span> (<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">8</span>):</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-4" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-4-6" class="code-annotation-target"><a href="#annotated-cell-4-6" aria-hidden="true" tabindex="-1"></a>    cuenta <span class="op">=</span> [comb(nfeat <span class="op">+</span> g, g) <span class="op">-</span> <span class="dv">1</span> <span class="cf">for</span> g <span class="kw">in</span> (<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">5</span>)]</span>
<span id="annotated-cell-4-7"><a href="#annotated-cell-4-7" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>nfeat<span class="sc">:10d}</span><span class="ss"> "</span> <span class="op">+</span> <span class="st">" "</span>.join(<span class="ss">f"</span><span class="sc">{</span>c<span class="sc">:10d}</span><span class="ss">"</span> <span class="cf">for</span> c <span class="kw">in</span> cuenta))</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-4" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-4" data-code-lines="6" data-code-annotation="1">El número de monomios de grado menor o igual que <span class="math inline">\(g\)</span> en <span class="math inline">\(p\)</span> variables es <span class="math inline">\(\binom{p+g}{g}\)</span>, y se resta uno para no contar el término constante, que ya está en la columna de unos.</span>
</dd>
</dl>
</div>
<div class="cell-output cell-output-stdout">
<pre><code> variables    grado 1    grado 2    grado 3    grado 5
         1          1          2          3          5
         2          2          5          9         20
         8          8         44        164       1286</code></pre>
</div>
</div>
<p>Con las ocho variables numéricas del capítulo 5, pasar a grado 2 son 44 características y a grado 3 son 164. La dimensión crece deprisa, y cada característica nueva es un parámetro más que hay que estimar con las mismas observaciones.</p>
<p>Entre esos productos hay uno de especial relevancia. Un término <span class="math inline">\(x_1x_2\)</span> hace que el efecto de <span class="math inline">\(x_1\)</span> sobre la predicción dependa del valor de <span class="math inline">\(x_2\)</span>, porque la derivada de <span class="math inline">\(w_0+w_1x_1+w_2x_2+w_3x_1x_2\)</span> respecto de <span class="math inline">\(x_1\)</span> vale <span class="math inline">\(w_1+w_3x_2\)</span>. Ese producto es una <strong>interacción</strong>: sin él, el efecto de <span class="math inline">\(x_1\)</span> sobre la predicción es el mismo cualquiera que sea el valor de <span class="math inline">\(x_2\)</span>. Lo observamos en la siguiente figura.</p>
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>x1 <span class="op">=</span> torch.linspace(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">100</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>casos <span class="op">=</span> [(<span class="st">"sin interacción, $w_3 = 0$"</span>, <span class="fl">0.0</span>),</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>         (<span class="st">"con interacción, $w_3 = 1.6$"</span>, <span class="fl">1.6</span>)]</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="fl">3.0</span>), sharey<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> panel, (titulo, w3) <span class="kw">in</span> <span class="bu">enumerate</span>(casos):</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> x2, color <span class="kw">in</span> [(<span class="fl">0.0</span>, AZUL), (<span class="fl">1.0</span>, NARANJA)]:</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>        ax[panel].plot(x1, <span class="fl">0.5</span> <span class="op">+</span> x1 <span class="op">+</span> <span class="fl">0.4</span> <span class="op">*</span> x2 <span class="op">+</span> w3 <span class="op">*</span> x1 <span class="op">*</span> x2,</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>                       color<span class="op">=</span>color, lw<span class="op">=</span><span class="fl">1.8</span>, label<span class="op">=</span><span class="ss">f"$x_2 = </span><span class="sc">{</span>x2<span class="sc">:.0f}</span><span class="ss">$"</span>)</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>    ax[panel].<span class="bu">set</span>(xlabel<span class="op">=</span><span class="st">"$x_1$"</span>, title<span class="op">=</span>titulo)</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].<span class="bu">set</span>(ylabel<span class="op">=</span><span class="st">"predicción"</span>)</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].legend(fontsize<span class="op">=</span><span class="fl">8.5</span>, loc<span class="op">=</span><span class="st">"upper left"</span>)</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="fig-interaccion" class="quarto-float quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<div aria-describedby="fig-interaccion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div id="6befa54f" class="cell" data-execution_count="9">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="06-complejidad_files/figure-html/cell-10-output-1.png" class="figure-img" width="1027" height="377"></p>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-margin quarto-float-caption quarto-float-fig margin-caption" id="fig-interaccion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.4: La predicción de <span class="math inline">\(w_0+w_1x_1+w_2x_2+w_3x_1x_2\)</span> frente a <span class="math inline">\(x_1\)</span>, para dos valores de <span class="math inline">\(x_2\)</span>. Sin el producto las dos rectas son paralelas. Con él las pendientes son <span class="math inline">\(w_1\)</span> y <span class="math inline">\(w_1+w_3\)</span>.
</figcaption>
</figure>
</div>
</section>
<section id="un-algoritmo-produce-modelos-distintos-con-muestras-distintas" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="un-algoritmo-produce-modelos-distintos-con-muestras-distintas">Un algoritmo produce modelos distintos con muestras distintas</h2>
<p>Hasta ahora hemos presentado una forma de construir una nueva clase de hipótesis más flexible. No obstante, hemos observado que el riesgo verdadero puede aumentar si nos excedemos con la complejidad (por ejemplo, subiendo demasiado el grado del polinomio).</p>
<p>Para entender por qué ocurre esto, no basta con mirar un único ajuste. Tenemos que evaluar el procedimiento de aprendizaje en su conjunto, estudiando qué sucede si aplicamos nuestro algoritmo a múltiples muestras de entrenamiento distintas extraídas del mismo universo.</p>
<p>En el siguiente experimento vamos a simular 2000 realidades alternativas. En cada una, extraeremos una muestra aleatoria independiente de 36 observaciones, ajustaremos un modelo polinómico y guardaremos la curva resultante. Haremos esto para los grados 1, 3 y 9.</p>
<div id="9aa8bd17" class="cell" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> muchos_ajustes(grado, n<span class="op">=</span><span class="dv">36</span>, repeticiones<span class="op">=</span>REPETICIONES, semilla<span class="op">=</span><span class="dv">0</span>):</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>    torch.manual_seed(semilla)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>    predicciones <span class="op">=</span> torch.empty(repeticiones, <span class="bu">len</span>(rejilla))</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> r <span class="kw">in</span> <span class="bu">range</span>(repeticiones):</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>        xr <span class="op">=</span> torch.rand(n) <span class="op">*</span> <span class="dv">2</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>        yr <span class="op">=</span> senal(xr) <span class="op">+</span> NOISE <span class="op">*</span> torch.randn(n)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>        w <span class="op">=</span> torch.linalg.lstsq(caracteristicas(xr, grado), yr).solution</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>        predicciones[r] <span class="op">=</span> caracteristicas(rejilla, grado) <span class="op">@</span> w</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> predicciones</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">3</span>, figsize<span class="op">=</span>(<span class="dv">9</span>, <span class="fl">2.8</span>), sharey<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> panel, grado <span class="kw">in</span> <span class="bu">enumerate</span>([<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">9</span>]):</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>    P <span class="op">=</span> muchos_ajustes(grado)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> r <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">0</span>, REPETICIONES, REPETICIONES <span class="op">//</span> <span class="dv">100</span>):</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>        ax[panel].plot(rejilla, P[r], color<span class="op">=</span>NARANJA, lw<span class="op">=</span><span class="fl">0.6</span>, alpha<span class="op">=</span><span class="fl">0.15</span>)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>    ax[panel].plot(rejilla, P.mean(<span class="dv">0</span>), color<span class="op">=</span>NARANJA, lw<span class="op">=</span><span class="fl">2.0</span>,</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>                   label<span class="op">=</span><span class="st">"modelo medio"</span>)</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>    ax[panel].plot(rejilla, senal(rejilla), color<span class="op">=</span>TINTA, lw<span class="op">=</span><span class="fl">1.5</span>,</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>                   label<span class="op">=</span><span class="st">"señal"</span>)</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>    ax[panel].<span class="bu">set</span>(xlabel<span class="op">=</span><span class="st">"$x$"</span>, title<span class="op">=</span><span class="ss">f"grado </span><span class="sc">{</span>grado<span class="sc">}</span><span class="ss">"</span>, ylim<span class="op">=</span>(<span class="op">-</span><span class="fl">2.2</span>, <span class="fl">2.2</span>))</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].<span class="bu">set</span>(ylabel<span class="op">=</span><span class="st">"$y$"</span>)</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].legend(fontsize<span class="op">=</span><span class="fl">8.5</span>, loc<span class="op">=</span><span class="st">"lower left"</span>)</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="fig-variabilidad" class="quarto-float quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<div aria-describedby="fig-variabilidad-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div id="688db974" class="cell" data-execution_count="11">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="06-complejidad_files/figure-html/cell-12-output-1.png" class="figure-img" width="1157" height="351"></p>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-margin quarto-float-caption quarto-float-fig margin-caption" id="fig-variabilidad-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.5: Cien de los dos mil ajustes obtenidos con muestras distintas de treinta y seis observaciones, para tres grados. Con grado 1 las rectas casi coinciden entre sí, pero su promedio no se parece a la señal. Con grado 9 el modelo medio sí calca la señal, pero cada curva individual es errática.
</figcaption>
</figure>
</div>
<p>En la figura se ven tres comportamientos marcadamente diferentes.</p>
<ul>
<li><p>Panel izquierdo (Grado 1): Modelo estable pero sistemáticamente equivocado. El modelo es tan rígido que apenas cambia de una muestra a otra; todas las líneas naranjas están muy juntas (baja varianza). Sin embargo, el modelo medio es incapaz de seguir la curvatura de la señal negra real (alto sesgo).</p></li>
<li><p>Panel derecho (Grado 9): Modelo inestable pero centrado. El modelo es tan flexible que persigue el ruido específico de cada muestra de 36 puntos, produciendo curvas que se disparan en todas direcciones (alta varianza). No obstante, si promediamos esas miles de curvas erráticas, el modelo medio calca la señal subyacente casi a la perfección (bajo sesgo).</p></li>
<li><p>El grado 3 (centro) queda entre los dos extremos: es lo bastante flexible para seguir la curva (bajo sesgo), pero lo bastante rígido para no seguir el ruido de cada muestra (baja varianza).</p></li>
</ul>
<p>A continuación, formalizamos matemáticamente este fenómeno.</p>
</section>
<section id="la-descomposición-sesgo-varianza" class="level2">
<h2 class="anchored" data-anchor-id="la-descomposición-sesgo-varianza">La descomposición sesgo-varianza</h2>
<p>Queremos responder a la siguiente pregunta: si aplicáramos un mismo procedimiento de ajuste (i.e.&nbsp;algoritmo y clase de hipótesis elegida) repetidas veces sobre distintas muestras de datos de un tamaño dado, ¿cuánto se equivocarían en promedio los modelos resultantes al predecir observaciones futuras?</p>
<p>Para formalizar esto, debemos separar el problema en dos niveles. Primero, fijaremos nuestra atención en una sola observación nueva con características <span class="math inline">\(\mathbf{x}\)</span> concretas (por ejemplo, <span class="math inline">\(x=1.5\)</span>). El error de predicción que cometeremos sobre esta observación depende de dos fuentes de aleatoriedad independientes:</p>
<ol type="1">
<li>La procedente de la muestra de entrenamiento (<span class="math inline">\(\mathcal{D}\)</span>): Nuestro modelo ajustado <span class="math inline">\(\hat{f}_{\mathcal{D}}\)</span> es una variable aleatoria, pues depende de la muestra <span class="math inline">\(\mathcal{D}\)</span> (que son <span class="math inline">\(n\)</span> extracciones independientes de la distribución <span class="math inline">\(P^\star\)</span> de <a href="02-aprender-minimizando.html#def-riesgo-verdadero" class="quarto-xref">Definición&nbsp;<span>2.3</span></a>) que nos haya tocado para entrenar. Por tanto, calcular el rendimiento promedio exige tomar la esperanza sobre todas las posibles muestras de entrenamiento. Escribimos este valor esperado como <span class="math inline">\(\mathbb{E}_{\mathcal{D}}\!\left[ \cdot \right]\)</span>. Con ella se define el <strong>modelo medio</strong>.</li>
</ol>
<p><span id="eq-modelo-medio"><span class="math display">\[
\bar{\hat{f}}(\mathbf{x})=\mathbb{E}_{\mathcal{D}}\!\left[ \hat{f}_{\mathcal{D}}(\mathbf{x}) \right] .
\tag{6.4}\]</span></span></p>
<p>El modelo medio es, punto a punto, la predicción que da el algoritmo en promedio sobre todas las muestras posibles de tamaño <span class="math inline">\(n\)</span>. No es un modelo que se pueda ajustar con unos datos concretos, porque para calcularlo hacen falta todas las muestras posibles: es la curva naranja gruesa de <a href="#fig-variabilidad" class="quarto-xref">Figura&nbsp;<span>6.5</span></a>, el promedio de las dos mil finas.</p>
<ol start="2" type="1">
<li>El ruido del dato futuro (<span class="math inline">\(\varepsilon\)</span>): El valor real <span class="math inline">\(Y\)</span> que intentamos predecir no es determinista, pues asumimos que el modelo generador de <a href="01-senal-ruido.html#def-modelo-gaussiano" class="quarto-xref">Definición&nbsp;<span>1.4</span></a> lo produce como <span class="math inline">\(Y = f(\mathbf{x}) + \varepsilon\)</span>. Este ruido es estadísticamente independiente de la muestra de entrenamiento <span class="math inline">\(\mathcal{D}\)</span>. De forma análoga al punto anterior, utilizaremos el operador <span class="math inline">\(\mathbb{E}_{\varepsilon}\!\left[ \cdot \right]\)</span> para denotar la esperanza sobre la distribución de este nuevo ruido, del cual asumimos que tiene media cero (<span class="math inline">\(\mathbb{E}_{\varepsilon}\!\left[ \varepsilon \right]=0\)</span>) y varianza constante (<span class="math inline">\(\mathrm{Var}\!\left( \varepsilon \right)=\sigma^2\)</span>).</li>
</ol>
<p>Para dar respuesta a la pregunta que abría la sección (cuánto se equivocaría en promedio nuestro procedimiento al predecir), debemos evaluar el error en este punto <span class="math inline">\(\mathbf{x}\)</span> promediando sobre ambas fuentes de aleatoriedad. Matemáticamente, esta métrica es la esperanza conjunta <span class="math inline">\(\mathbb{E}_{\mathcal{D},\varepsilon}\!\left[ (Y - \hat{f}_{\mathcal{D}}(\mathbf{x}))^2 \right]\)</span>. El teorema siguiente descompone esta cantidad en tres términos. Para que la identidad se cumpla, hacen falta cuatro supuestos:</p>
<ol type="1">
<li><p>Pérdida cuadrática. La descomposición es una propiedad algebraica exclusiva del error cuadrático; con otra función de pérdida no existe una descomposición análoga.</p></li>
<li><p>Muestra aleatoria y ajuste determinista. <span class="math inline">\(\mathcal{D}\)</span> está formada por <span class="math inline">\(n\)</span> extracciones independientes de <span class="math inline">\(P^\star\)</span>, y el procedimiento de ajuste es una función determinista de <span class="math inline">\(\mathcal{D}\)</span>: toda la aleatoriedad de nuestro modelo proviene exclusivamente de la muestra.</p></li>
<li><p>Observación futura independiente. El par <span class="math inline">\((\mathbf{x},Y)\)</span> que se predice no pertenece a <span class="math inline">\(\mathcal{D}\)</span>, y su ruido intrínseco <span class="math inline">\(\varepsilon\)</span> es independiente de la muestra de entrenamiento y tiene media cero.</p></li>
<li><p>Varianza del ruido constante. <span class="math inline">\(\mathrm{Var}\!\left( \varepsilon \right)=\sigma^2\)</span> no depende de <span class="math inline">\(\mathbf{x}\)</span>. Sin esto, al promediar posteriormente sobre todo el espacio de características <span class="math inline">\(X\)</span>, el término del ruido no sería un único número <span class="math inline">\(\sigma^2\)</span>.</p></li>
</ol>
<div id="thm-descomposicion" class="theorem">
<p><span class="theorem-title"><strong>Teorema 6.1 (Descomposición sesgo-varianza)</strong></span> Fijado un punto <span class="math inline">\(\mathbf{x}\)</span>, sea <span class="math inline">\(Y = f(\mathbf{x}) + \varepsilon\)</span> la observación futura real. Sea <span class="math inline">\(\hat{f}_{\mathcal{D}}(\mathbf{x})\)</span> la predicción de nuestro algoritmo entrenado con la muestra aleatoria <span class="math inline">\(\mathcal{D}\)</span>, y sea <span class="math inline">\(\bar{\hat{f}}(\mathbf{x})\)</span> el modelo medio de <a href="#eq-modelo-medio" class="quarto-xref">Ecuación&nbsp;<span>6.4</span></a>].</p>
<p>Bajo los cuatro supuestos anteriores, el error cuadrático esperado se descompone en:</p>
<p><span id="eq-descomposicion"><span class="math display">\[
\mathbb{E}_{\mathcal{D},\varepsilon}\!\left[ (Y-\hat{f}_{\mathcal{D}}(\mathbf{x}))^2 \right] =\underbrace{\sigma^2}_{\text{ruido}} +\underbrace{\bigl(f(\mathbf{x}) - \bar{\hat{f}}(\mathbf{x})\bigr)^2}_{\text{sesgo}^2} +\underbrace{\mathbb{E}_{\mathcal{D}}\!\left[ (\hat{f}_{\mathcal{D}}(\mathbf{x})-\bar{\hat{f}}(\mathbf{x}))^2 \right]}_{\text{varianza}} .
\tag{6.5}\]</span></span></p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Demostración</em>. </span>Para aligerar la notación, escribiremos <span class="math inline">\(\hat{f}=\hat{f}_{\mathcal{D}}(\mathbf{x})\)</span>, <span class="math inline">\(f=f(\mathbf{x})\)</span> y <span class="math inline">\(\bar{\hat{f}}=\bar{\hat{f}}(\mathbf{x})\)</span>. La demostración comienza expandiendo el error; para ello, sustituimos <span class="math inline">\(Y\)</span> por su definición (<span class="math inline">\(f+ \varepsilon\)</span>) y sumamos y restamos el modelo medio <span class="math inline">\(\bar{\hat{f}}\)</span>:</p>
<p><span class="math display">\[
Y-\hat{f}= (f+ \varepsilon) - \hat{f}= \varepsilon + (f-\bar{\hat{f}}) + (\bar{\hat{f}}-\hat{f})
\]</span></p>
<p>Ahora elevamos esta suma de tres elementos al cuadrado. Obtendremos los tres cuadrados individuales y tres términos cruzados:</p>
<p><span class="math display">\[
(Y-\hat{f})^2 = \varepsilon^2 + (f-\bar{\hat{f}})^2 + (\bar{\hat{f}}-\hat{f})^2 + 2\varepsilon(f-\bar{\hat{f}}) + 2\varepsilon(\bar{\hat{f}}-\hat{f}) + 2(f-\bar{\hat{f}})(\bar{\hat{f}}-\hat{f})
\]</span></p>
<p>Al aplicar la esperanza conjunta <span class="math inline">\(\mathbb{E}_{\mathcal{D},\varepsilon}\!\left[ \cdot \right]\)</span>, la linealidad de la esperanza nos permite analizar cada componente por separado. Veamos paso a paso cómo los tres términos cruzados se anulan:</p>
<ol type="1">
<li><p><strong>El cruce entre el ruido y el sesgo:</strong> <span class="math display">\[
\mathbb{E}_{\mathcal{D},\varepsilon}\!\left[ 2\varepsilon(f-\bar{\hat{f}}) \right] = 2(f-\bar{\hat{f}})\,\mathbb{E}_{\varepsilon}\!\left[ \varepsilon \right] = 0
\]</span> Una vez fijado <span class="math inline">\(\mathbf{x}\)</span>, tanto la señal verdadera <span class="math inline">\(f\)</span> como el modelo medio <span class="math inline">\(\bar{\hat{f}}\)</span> son constantes (no dependen de la muestra concreta ni del ruido). Por tanto, salen fuera de la esperanza. Como asumimos que el ruido tiene media cero (<span class="math inline">\(\mathbb{E}_{\varepsilon}\!\left[ \varepsilon \right]=0\)</span>), todo el término se anula.</p></li>
<li><p><strong>El cruce entre el ruido y la varianza:</strong> <span class="math display">\[
\mathbb{E}_{\mathcal{D},\varepsilon}\!\left[ 2\varepsilon(\bar{\hat{f}}-\hat{f}) \right] = 2\,\mathbb{E}_{\varepsilon}\!\left[ \varepsilon \right]\,\mathbb{E}_{\mathcal{D}}\!\left[ \bar{\hat{f}}-\hat{f} \right] = 0
\]</span> Aquí resulta vital el tercer supuesto. Como el ruido de la observación futura (<span class="math inline">\(\varepsilon\)</span>) es estadísticamente independiente de la muestra de entrenamiento (<span class="math inline">\(\mathcal{D}\)</span>), la esperanza conjunta de su producto se separa en el producto de sus esperanzas individuales. Al ser <span class="math inline">\(\mathbb{E}_{\varepsilon}\!\left[ \varepsilon \right]=0\)</span>, el término entero desaparece.</p></li>
<li><p><strong>El cruce entre el sesgo y la varianza:</strong> <span class="math display">\[ \mathbb{E}_{\mathcal{D},\varepsilon}\!\left[ 2(f-\bar{\hat{f}})(\bar{\hat{f}}-\hat{f}) \right] = 2(f-\bar{\hat{f}})\,\mathbb{E}_{\mathcal{D}}\!\left[ \bar{\hat{f}}-\hat{f} \right] = 0 \]</span> Este término no contiene <span class="math inline">\(\varepsilon\)</span>, por lo que la esperanza actúa únicamente sobre <span class="math inline">\(\mathcal{D}\)</span>. La parte constante <span class="math inline">\((f-\bar{\hat{f}})\)</span> sale fuera. Por la propia definición del modelo medio en <a href="#eq-modelo-medio" class="quarto-xref">Ecuación&nbsp;<span>6.4</span></a>, la esperanza de las desviaciones de un modelo respecto a su propia media es cero: <span class="math inline">\(\mathbb{E}_{\mathcal{D}}\!\left[ \bar{\hat{f}}-\hat{f} \right] = \bar{\hat{f}} - \bar{\hat{f}} = 0\)</span>.</p></li>
</ol>
<p>Al anularse todos los cruces, solo sobreviven las esperanzas de los tres cuadrados individuales:</p>
<p><span class="math display">\[
\mathbb{E}_{\varepsilon}\!\left[ \varepsilon^2 \right] + (f-\bar{\hat{f}})^2 + \mathbb{E}_{\mathcal{D}}\!\left[ (\bar{\hat{f}}-\hat{f})^2 \right]
\]</span></p>
<p>Como el ruido tiene media cero, sabemos que <span class="math inline">\(\mathbb{E}_{\varepsilon}\!\left[ \varepsilon^2 \right] = \mathrm{Var}\!\left( \varepsilon \right) = \sigma^2\)</span>. Sustituyendo esto, obtenemos exactamente la identidad de <a href="#eq-descomposicion" class="quarto-xref">Ecuación&nbsp;<span>6.5</span></a>.</p>
</div>
<p>Estos tres sumandos no solo explican por qué nos equivocamos, sino que nos dan el diagnóstico exacto de <strong>cómo de bien va a funcionar nuestro procedimiento de aprendizaje</strong> ante datos futuros. Nos dicen si nuestras predicciones fallarán porque somos demasiado rígidos (sesgo), demasiado inestables (varianza) o porque la naturaleza es inherentemente impredecible (ruido):</p>
<ul>
<li><p><strong>El ruido</strong> (<span class="math inline">\(\sigma^2\)</span>) es la varianza intrínseca de <span class="math inline">\(Y\)</span> una vez fijado <span class="math inline">\(\mathbf{x}\)</span>. Ningún procedimiento, por muchos datos que tenga o muy avanzado que sea el algoritmo, bajará de aquí: es el suelo inexpugnable del error que el capítulo 2 anunció.</p></li>
<li><p><strong>El sesgo al cuadrado</strong> mide la distancia entre la señal verdadera <span class="math inline">\(f\)</span> y nuestro modelo medio <span class="math inline">\(\bar{\hat{f}}\)</span> (la separación entre la curva negra y la curva gruesa naranja de <a href="#fig-variabilidad" class="quarto-xref">Figura&nbsp;<span>6.5</span></a>). Este error <strong>no se atenúa con más datos</strong>, ya que un procedimiento demasiado rígido (como ajustar líneas rectas) nunca podrá adoptar una forma curva por muchas observaciones que reciba. Depende exclusivamente de la clase de hipótesis elegida. <strong>La única forma de reducir el sesgo es aumentar la complejidad</strong> del modelo (por ejemplo, subiendo el grado del polinomio o añadiendo variables), dotando a nuestro procedimiento de la capacidad geométrica necesaria para calcar la señal real.</p></li>
<li><p><strong>La varianza</strong> mide cuánto se mueve un modelo concreto <span class="math inline">\(\hat{f}_{\mathcal{D}}\)</span> alrededor de su propio promedio <span class="math inline">\(\bar{\hat{f}}\)</span> por culpa de la muestra específica que le tocó (la dispersión de las finas líneas naranjas). Es el precio directo de la flexibilidad: al aumentar la complejidad para reducir el sesgo, le damos al algoritmo tanta libertad que empieza a perseguir el ruido de cada muestra. Sin embargo, a diferencia del sesgo, la varianza <strong>sí se atenúa con más datos</strong>, ya que un conjunto de entrenamiento más grande estabiliza el algoritmo y evita que el modelo dé bandazos.</p></li>
</ul>
<p>La ecuación anterior detalla el error para un solo punto fijo <span class="math inline">\(\mathbf{x}\)</span>. Para calcular el riesgo esperado de <a href="04-evaluacion.html#def-riesgo-procedimiento" class="quarto-xref">Definición&nbsp;<span>4.4</span></a>, solo nos falta un último paso: promediar ese resultado sobre todas las posibles características <span class="math inline">\(\mathbf{x}\)</span> que nos encontraremos en la realidad (es decir, tomar la esperanza sobre la distribución marginal de <span class="math inline">\(X\)</span> bajo <span class="math inline">\(P^\star\)</span>).</p>
<p>Como la esperanza es un operador lineal, la descomposición sobrevive intacta a nivel global:</p>
<p><span id="eq-descomposicion-global"><span class="math display">\[
\bar{R}_{n}=\mathbb{E}_{\mathcal{D}}\!\left[ R(\hat{f}_{\mathcal{D}}) \right]
=\sigma^2
+\mathbb{E}_{X}\!\left[ \bigl(f(X)-\bar{\hat{f}}(X)\bigr)^2 \right]
+\mathbb{E}_{X}\!\left[ \mathbb{E}_{\mathcal{D}}\!\left[ \bigl(\hat{f}_{\mathcal{D}}(X)-\bar{\hat{f}}(X)\bigr)^2 \right] \right] .
\tag{6.6}\]</span></span></p>
<p>Ahora sí, podemos medir de forma rigurosa estos tres componentes sobre el experimento simulado de la sección anterior.</p>
<div id="1ad15f6b" class="cell" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> descompone(grado, n<span class="op">=</span><span class="dv">36</span>, repeticiones<span class="op">=</span>REPETICIONES, semilla<span class="op">=</span><span class="dv">0</span>):</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>    P <span class="op">=</span> muchos_ajustes(grado, n<span class="op">=</span>n, repeticiones<span class="op">=</span>repeticiones,</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>                       semilla<span class="op">=</span>semilla)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>    sesgo2 <span class="op">=</span> ((P.mean(<span class="dv">0</span>) <span class="op">-</span> senal(rejilla)) <span class="op">**</span> <span class="dv">2</span>).mean().item()</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>    varianza <span class="op">=</span> P.var(<span class="dv">0</span>, unbiased<span class="op">=</span><span class="va">False</span>).mean().item()</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> sesgo2, varianza, NOISE <span class="op">**</span> <span class="dv">2</span> <span class="op">+</span> sesgo2 <span class="op">+</span> varianza</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'grado'</span><span class="sc">:&gt;6}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'sesgo^2'</span><span class="sc">:&gt;9}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'varianza'</span><span class="sc">:&gt;10}</span><span class="ss"> "</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="sc">{</span><span class="st">'ruido'</span><span class="sc">:&gt;8}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'total'</span><span class="sc">:&gt;10}</span><span class="ss">"</span>)</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>descomposicion <span class="op">=</span> {}</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> grado <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">0</span>, <span class="dv">10</span>):</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>    sesgo2, varianza, total <span class="op">=</span> descompone(grado)</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>    descomposicion[grado] <span class="op">=</span> (sesgo2, varianza, total)</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>grado<span class="sc">:6d}</span><span class="ss"> </span><span class="sc">{</span>sesgo2<span class="sc">:9.4f}</span><span class="ss"> </span><span class="sc">{</span>varianza<span class="sc">:10.4f}</span><span class="ss"> "</span></span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"</span><span class="sc">{</span>NOISE <span class="op">**</span> <span class="dv">2</span><span class="sc">:8.4f}</span><span class="ss"> </span><span class="sc">{</span>total<span class="sc">:10.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> grado   sesgo^2   varianza    ruido      total
     0    0.4988     0.0146   0.0400     0.5533
     1    0.1980     0.0160   0.0400     0.2541
     2    0.1990     0.0339   0.0400     0.2729
     3    0.0046     0.0066   0.0400     0.0512
     4    0.0049     0.0114   0.0400     0.0563
     5    0.0000     0.0134   0.0400     0.0534
     6    0.0000     0.0281   0.0400     0.0682
     7    0.0000     0.0843   0.0400     0.1243
     8    0.0001     0.3838   0.0400     0.4239
     9    0.0029     3.1114   0.0400     3.1543</code></pre>
</div>
</div>
<p>La última columna es la suma de los tres términos, y <a href="#eq-descomposicion" class="quarto-xref">Ecuación&nbsp;<span>6.5</span></a> dice que esa suma es el riesgo esperado. Conviene comprobarlo midiendo el riesgo esperado por el otro camino: el promedio, sobre los dos mil ajustes, del error cuadrático que cada uno comete contra la señal.</p>
<div id="a00d5fc8" class="cell" data-execution_count="13">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="annotated-cell-7"><pre class="sourceCode python code-annotation-code code-with-copy code-annotated"><code class="sourceCode python"><span id="annotated-cell-7-1"><a href="#annotated-cell-7-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> riesgo_directo(grado, n<span class="op">=</span><span class="dv">36</span>, repeticiones<span class="op">=</span>REPETICIONES, semilla<span class="op">=</span><span class="dv">0</span>):</span>
<span id="annotated-cell-7-2"><a href="#annotated-cell-7-2" aria-hidden="true" tabindex="-1"></a>    P <span class="op">=</span> muchos_ajustes(grado, n<span class="op">=</span>n, repeticiones<span class="op">=</span>repeticiones,</span>
<span id="annotated-cell-7-3"><a href="#annotated-cell-7-3" aria-hidden="true" tabindex="-1"></a>                       semilla<span class="op">=</span>semilla)</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-7" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-7-4" class="code-annotation-target"><a href="#annotated-cell-7-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> NOISE <span class="op">**</span> <span class="dv">2</span> <span class="op">+</span> ((P <span class="op">-</span> senal(rejilla)) <span class="op">**</span> <span class="dv">2</span>).mean().item()</span>
<span id="annotated-cell-7-5"><a href="#annotated-cell-7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-7-6"><a href="#annotated-cell-7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-7-7"><a href="#annotated-cell-7-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'grado'</span><span class="sc">:&gt;6}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'suma de los tres'</span><span class="sc">:&gt;18}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'directo'</span><span class="sc">:&gt;10}</span><span class="ss">"</span>)</span>
<span id="annotated-cell-7-8"><a href="#annotated-cell-7-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> grado <span class="kw">in</span> (<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">9</span>):</span>
<span id="annotated-cell-7-9"><a href="#annotated-cell-7-9" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>grado<span class="sc">:6d}</span><span class="ss"> </span><span class="sc">{</span>descomposicion[grado][<span class="dv">2</span>]<span class="sc">:18.4f}</span><span class="ss"> "</span></span>
<span id="annotated-cell-7-10"><a href="#annotated-cell-7-10" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"</span><span class="sc">{</span>riesgo_directo(grado)<span class="sc">:10.4f}</span><span class="ss">"</span>)</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-7" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-7" data-code-lines="4" data-code-annotation="1">Se promedia sobre los dos mil ajustes y sobre la rejilla a la vez, sin separar sesgo de varianza. Los dos caminos usan las mismas dos mil muestras, así que lo que se comprueba es la identidad algebraica de <a href="#eq-descomposicion" class="quarto-xref">Ecuación&nbsp;<span>6.5</span></a>, no el valor de <span class="math inline">\(\sigma^2\)</span>, que aquí se suma por conocido.</span>
</dd>
</dl>
</div>
<div class="cell-output cell-output-stdout">
<pre><code> grado   suma de los tres    directo
     1             0.2541     0.2541
     3             0.0512     0.0512
     9             3.1543     3.1543</code></pre>
</div>
</div>
<p>La tabla revela la tensión fundamental del aprendizaje automático:</p>
<ul>
<li><p>El sesgo al cuadrado cae drásticamente desde <span class="math inline">\(0.4988\)</span> (grado 0) hasta <span class="math inline">\(0.0046\)</span> al llegar al grado 3. A partir de ahí, apenas varía. La razón geométrica es simple: un polinomio cúbico ya es lo suficientemente flexible para imitar la forma de la onda <span class="math inline">\(\sin(\pi x)\)</span> en este intervalo. Añadir potencias mayores no acerca mucho más el modelo medio a la señal real porque el problema de “falta de capacidad” ya está resuelto.</p></li>
<li><p><strong>La varianza explota:</strong> La varianza hace exactamente lo contrario. Se mantiene baja hasta el grado 3 (<span class="math inline">\(0.0066\)</span>) y luego se descontrola subiendo hasta <span class="math inline">\(3.1114\)</span> para grado 9. El motivo es la sobreparametrización: al intentar estimar 10 parámetros con solo 36 observaciones repartidas al azar, el modelo tiene demasiada libertad. El polinomio persigue el ruido específico de cada muestra y se dispara en los huecos entre los puntos, provocando que la curva cambie radicalmente de una muestra a otra.</p></li>
<li><p><strong>El riesgo total sigue una curva en U:</strong> La suma de los tres términos (sesgo, varianza y el ruido constante de <span class="math inline">\(0.0400\)</span>) es el riesgo esperado. Al chocar la caída del sesgo con la explosión de la varianza, el riesgo total forma una U. El mínimo no está en los extremos, sino en el interior: el grado 3 encuentra el equilibrio óptimo.</p></li>
</ul>
</section>
<section id="la-curva-en-u-y-lo-que-la-validación-cruzada-logra-ver" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="la-curva-en-u-y-lo-que-la-validación-cruzada-logra-ver">La curva en U y lo que la validación cruzada logra ver</h2>
<p>La suma de la sección anterior (el riesgo esperado total) solo se puede calcular porque en esta simulación conocemos la señal verdadera y podemos promediar miles de muestras. En el mundo real, solo tenemos una única muestra y la señal es desconocida.</p>
<p>¿Cómo estimamos entonces esta curva en la práctica? Recordando lo que establecimos en <a href="04-evaluacion.html#sec-kfold" class="quarto-xref"><span>Sección 4.4.2</span></a>: la validación cruzada no evalúa el modelo final, sino que <strong>estima el riesgo esperado del procedimiento</strong> de <a href="04-evaluacion.html#def-riesgo-procedimiento" class="quarto-xref">Definición&nbsp;<span>4.4</span></a>. Al partir nuestra única muestra en bloques y ajustar múltiples modelos, la cantidad de <a href="04-evaluacion.html#eq-cv" class="quarto-xref">Ecuación&nbsp;<span>4.2</span></a> simula empíricamente esa esperanza <span class="math inline">\(\mathbb{E}_{\mathcal{D}}\!\left[ \cdot \right]\)</span> teórica. Conviene comprobar qué es lo que realmente logra ver frente a la verdad teórica.</p>
<div id="fad9e9de" class="cell" data-execution_count="14">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> KFold</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> cv_riesgo(grado, x, y, n_bloques<span class="op">=</span><span class="dv">5</span>, semilla<span class="op">=</span><span class="dv">9</span>):</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    particion <span class="op">=</span> KFold(n_splits<span class="op">=</span>n_bloques, shuffle<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>                      random_state<span class="op">=</span>semilla)</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>    riesgos <span class="op">=</span> []</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i_ajuste, i_val <span class="kw">in</span> particion.split(x.numpy()):</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>        w <span class="op">=</span> torch.linalg.lstsq(caracteristicas(x[i_ajuste], grado),</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>                               y[i_ajuste]).solution</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>        riesgos.append(((caracteristicas(x[i_val], grado) <span class="op">@</span> w</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>                         <span class="op">-</span> y[i_val]) <span class="op">**</span> <span class="dv">2</span>).mean().item())</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="bu">float</span>(np.mean(riesgos)), riesgos</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'grado'</span><span class="sc">:&gt;6}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'train'</span><span class="sc">:&gt;9}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'CV(5)'</span><span class="sc">:&gt;9}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'ee'</span><span class="sc">:&gt;7}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'esperado'</span><span class="sc">:&gt;10}</span><span class="ss">"</span>)</span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>tabla_cv <span class="op">=</span> {}</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>bloques_cv <span class="op">=</span> {}</span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> grado <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">0</span>, <span class="dv">10</span>):</span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a>    cv, bloques <span class="op">=</span> cv_riesgo(grado, x, y)</span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a>    w <span class="op">=</span> ajusta(x, y, grado)</span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a>    tabla_cv[grado] <span class="op">=</span> cv</span>
<span id="cb16-23"><a href="#cb16-23" aria-hidden="true" tabindex="-1"></a>    bloques_cv[grado] <span class="op">=</span> np.array(bloques)</span>
<span id="cb16-24"><a href="#cb16-24" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>grado<span class="sc">:6d}</span><span class="ss"> "</span></span>
<span id="cb16-25"><a href="#cb16-25" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"</span><span class="sc">{</span>((caracteristicas(x, grado) <span class="op">@</span> w <span class="op">-</span> y) <span class="op">**</span> <span class="dv">2</span>)<span class="sc">.</span>mean()<span class="sc">:9.4f}</span><span class="ss"> "</span></span>
<span id="cb16-26"><a href="#cb16-26" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"</span><span class="sc">{</span>cv<span class="sc">:9.4f}</span><span class="ss"> </span><span class="sc">{</span>np<span class="sc">.</span>std(bloques, ddof<span class="op">=</span><span class="dv">1</span>) <span class="op">/</span> np<span class="sc">.</span>sqrt(<span class="dv">5</span>)<span class="sc">:7.4f}</span><span class="ss"> "</span></span>
<span id="cb16-27"><a href="#cb16-27" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"</span><span class="sc">{</span>descomposicion[grado][<span class="dv">2</span>]<span class="sc">:10.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> grado     train     CV(5)      ee   esperado
     0    0.4608    0.4761  0.0787     0.5533
     1    0.1538    0.1766  0.0231     0.2541
     2    0.1526    0.1975  0.0300     0.2729
     3    0.0217    0.0308  0.0054     0.0512
     4    0.0194    0.0323  0.0071     0.0563
     5    0.0178    0.0288  0.0081     0.0534
     6    0.0160    0.0312  0.0055     0.0682
     7    0.0159    0.0309  0.0055     0.1243
     8    0.0147    0.0286  0.0052     0.4239
     9    0.0146    0.1074  0.0636     3.1543</code></pre>
</div>
</div>
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>grados <span class="op">=</span> <span class="bu">list</span>(<span class="bu">range</span>(<span class="dv">10</span>))</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="fl">8.4</span>, <span class="fl">3.2</span>))</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].plot(grados, [descomposicion[g][<span class="dv">0</span>] <span class="cf">for</span> g <span class="kw">in</span> grados], marker<span class="op">=</span><span class="st">"o"</span>, ms<span class="op">=</span><span class="dv">4</span>,</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>           color<span class="op">=</span>AZUL, label<span class="op">=</span><span class="st">"sesgo$^2$"</span>)</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].plot(grados, [descomposicion[g][<span class="dv">1</span>] <span class="cf">for</span> g <span class="kw">in</span> grados], marker<span class="op">=</span><span class="st">"s"</span>, ms<span class="op">=</span><span class="dv">4</span>,</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>           color<span class="op">=</span>NARANJA, label<span class="op">=</span><span class="st">"varianza"</span>)</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].plot(grados, [descomposicion[g][<span class="dv">2</span>] <span class="cf">for</span> g <span class="kw">in</span> grados], marker<span class="op">=</span><span class="st">"^"</span>, ms<span class="op">=</span><span class="dv">4</span>,</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>           color<span class="op">=</span>TINTA, label<span class="op">=</span><span class="st">"riesgo esperado"</span>)</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].axhline(NOISE <span class="op">**</span> <span class="dv">2</span>, color<span class="op">=</span>GRIS, lw<span class="op">=</span><span class="dv">1</span>, linestyle<span class="op">=</span><span class="st">":"</span>,</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>              label<span class="op">=</span><span class="vs">r"ruido </span><span class="dv">$\s</span><span class="vs">igma</span><span class="dv">^</span><span class="vs">2</span><span class="dv">$</span><span class="vs">"</span>)</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].<span class="bu">set</span>(xlabel<span class="op">=</span><span class="st">"grado del polinomio"</span>, ylabel<span class="op">=</span><span class="st">"riesgo cuadrático medio"</span>,</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>          yscale<span class="op">=</span><span class="st">"log"</span>, title<span class="op">=</span><span class="st">"con la señal conocida"</span>)</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].legend(fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].plot(grados, [tabla_cv[g] <span class="cf">for</span> g <span class="kw">in</span> grados], marker<span class="op">=</span><span class="st">"o"</span>, ms<span class="op">=</span><span class="dv">4</span>,</span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>           color<span class="op">=</span>NARANJA, label<span class="op">=</span><span class="st">"CV(5)"</span>)</span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].plot(grados, [descomposicion[g][<span class="dv">2</span>] <span class="cf">for</span> g <span class="kw">in</span> grados], marker<span class="op">=</span><span class="st">"^"</span>, ms<span class="op">=</span><span class="dv">4</span>,</span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a>           color<span class="op">=</span>TINTA, label<span class="op">=</span><span class="st">"riesgo esperado"</span>)</span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].axhline(NOISE <span class="op">**</span> <span class="dv">2</span>, color<span class="op">=</span>GRIS, lw<span class="op">=</span><span class="dv">1</span>, linestyle<span class="op">=</span><span class="st">":"</span>)</span>
<span id="cb18-22"><a href="#cb18-22" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].<span class="bu">set</span>(xlabel<span class="op">=</span><span class="st">"grado del polinomio"</span>, yscale<span class="op">=</span><span class="st">"log"</span>,</span>
<span id="cb18-23"><a href="#cb18-23" aria-hidden="true" tabindex="-1"></a>          title<span class="op">=</span><span class="st">"con una sola muestra"</span>)</span>
<span id="cb18-24"><a href="#cb18-24" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].legend(fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb18-25"><a href="#cb18-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-26"><a href="#cb18-26" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="fig-curva-u" class="quarto-float quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<div aria-describedby="fig-curva-u-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div id="c757d39e" class="cell" data-execution_count="15">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="06-complejidad_files/figure-html/cell-16-output-1.png" class="figure-img" width="1078" height="403"></p>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-margin quarto-float-caption quarto-float-fig margin-caption" id="fig-curva-u-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.6: A la izquierda, la descomposición: la rama izquierda de la curva del riesgo es sesgo y la derecha es varianza. A la derecha, lo que se puede calcular con una sola muestra de treinta y seis observaciones. La validación cruzada reproduce la rama izquierda con nitidez y la derecha solo a partir del grado 9.
</figcaption>
</figure>
</div>
<p>La comparación de los dos paneles nos advierte de los límites de medir con muestras pequeñas. La validación cruzada ve la rama del sesgo perfectamente: distingue sin ambigüedad los grados 0, 1 y 2 del resto. Sin embargo, en la rama de la varianza fracasa: entre los grados 3 y 8 devuelve valores estancados entre <span class="math inline">\(0.0286\)</span> y <span class="math inline">\(0.0323\)</span>, colocando su aparente mínimo en el grado 8.</p>
<p>Aquí debemos separar rigurosamente dos cantidades que conviene no confundir:</p>
<ol type="1">
<li><p>El error de estimación: La validación cruzada nos promete que el riesgo del grado 8 es <span class="math inline">\(0.0286\)</span>, pero la verdad teórica es <span class="math inline">\(0.4239\)</span>. La herramienta es demasiado optimista y se equivoca por un factor de quince al evaluar este candidato.</p></li>
<li><p>El coste de elegir mal: Si caemos en la trampa del mínimo aparente y entregamos el grado 8, el riesgo real será <span class="math inline">\(0.4239\)</span>. Si entregamos el grado 3, el riesgo será de <span class="math inline">\(0.0512\)</span>. Elegir mal multiplica nuestro error en producción por ocho.</p></li>
</ol>
<p>¿Por qué se equivoca la CV? Es <a href="04-evaluacion.html#prp-minimo-sesgado" class="quarto-xref">Proposición&nbsp;<span>4.3</span></a> otra vez: el mínimo de varias estimaciones ruidosas es optimista y cae donde el ruido lo lleve. La regla de un error típico (<a href="04-evaluacion.html#def-regla-un-error-tipico" class="quarto-xref">Definición&nbsp;<span>4.7</span></a>) no mejora esa estimación, pero sí cambia la decisión. Apliquémosla sobre esta tabla, con sus tres pasos.</p>
<div id="630a44ac" class="cell" data-execution_count="16">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="annotated-cell-9"><pre class="sourceCode python code-annotation-code code-with-copy code-annotated"><code class="sourceCode python"><span id="annotated-cell-9-1"><a href="#annotated-cell-9-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> compara_con_campeon(grado, campeon, bloques):</span>
<span id="annotated-cell-9-2"><a href="#annotated-cell-9-2" aria-hidden="true" tabindex="-1"></a>    d <span class="op">=</span> bloques[grado] <span class="op">-</span> bloques[campeon]</span>
<span id="annotated-cell-9-3"><a href="#annotated-cell-9-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> d.mean(), d.std(ddof<span class="op">=</span><span class="dv">1</span>) <span class="op">/</span> np.sqrt(<span class="bu">len</span>(d))</span>
<span id="annotated-cell-9-4"><a href="#annotated-cell-9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-9-5"><a href="#annotated-cell-9-5" aria-hidden="true" tabindex="-1"></a></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-9" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-9-6" class="code-annotation-target"><a href="#annotated-cell-9-6" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> regla_un_error_tipico(bloques):</span>
<span id="annotated-cell-9-7"><a href="#annotated-cell-9-7" aria-hidden="true" tabindex="-1"></a>    campeon <span class="op">=</span> <span class="bu">min</span>(bloques, key<span class="op">=</span><span class="kw">lambda</span> g: bloques[g].mean())</span>
<span id="annotated-cell-9-8"><a href="#annotated-cell-9-8" aria-hidden="true" tabindex="-1"></a>    dentro <span class="op">=</span> []</span>
<span id="annotated-cell-9-9"><a href="#annotated-cell-9-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> grado <span class="kw">in</span> <span class="bu">range</span>(campeon):</span>
<span id="annotated-cell-9-10"><a href="#annotated-cell-9-10" aria-hidden="true" tabindex="-1"></a>        dif, ee_dif <span class="op">=</span> compara_con_campeon(grado, campeon, bloques)</span>
<span id="annotated-cell-9-11"><a href="#annotated-cell-9-11" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> dif <span class="op">&lt;</span> ee_dif:</span>
<span id="annotated-cell-9-12"><a href="#annotated-cell-9-12" aria-hidden="true" tabindex="-1"></a>            dentro.append(grado)</span>
<span id="annotated-cell-9-13"><a href="#annotated-cell-9-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> campeon, <span class="bu">min</span>(dentro, default<span class="op">=</span>campeon)</span>
<span id="annotated-cell-9-14"><a href="#annotated-cell-9-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-9-15"><a href="#annotated-cell-9-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-9-16"><a href="#annotated-cell-9-16" aria-hidden="true" tabindex="-1"></a>campeon, entregado <span class="op">=</span> regla_un_error_tipico(bloques_cv)</span>
<span id="annotated-cell-9-17"><a href="#annotated-cell-9-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-9-18"><a href="#annotated-cell-9-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"campeón: grado </span><span class="sc">{</span>campeon<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="annotated-cell-9-19"><a href="#annotated-cell-9-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'grado'</span><span class="sc">:&gt;6}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'diferencia'</span><span class="sc">:&gt;12}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'error típico'</span><span class="sc">:&gt;14}</span><span class="ss"> "</span></span>
<span id="annotated-cell-9-20"><a href="#annotated-cell-9-20" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="sc">{</span><span class="st">'cociente'</span><span class="sc">:&gt;10}</span><span class="ss">"</span>)</span>
<span id="annotated-cell-9-21"><a href="#annotated-cell-9-21" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> grado <span class="kw">in</span> <span class="bu">range</span>(campeon):</span>
<span id="annotated-cell-9-22"><a href="#annotated-cell-9-22" aria-hidden="true" tabindex="-1"></a>    dif, ee_dif <span class="op">=</span> compara_con_campeon(grado, campeon, bloques_cv)</span>
<span id="annotated-cell-9-23"><a href="#annotated-cell-9-23" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>grado<span class="sc">:6d}</span><span class="ss"> </span><span class="sc">{</span>dif<span class="sc">:+12.4f}</span><span class="ss"> </span><span class="sc">{</span>ee_dif<span class="sc">:14.4f}</span><span class="ss"> "</span></span>
<span id="annotated-cell-9-24"><a href="#annotated-cell-9-24" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"</span><span class="sc">{</span>dif <span class="op">/</span> ee_dif<span class="sc">:10.2f}</span><span class="ss">"</span>)</span>
<span id="annotated-cell-9-25"><a href="#annotated-cell-9-25" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">grado entregado: </span><span class="sc">{</span>entregado<span class="sc">}</span><span class="ss">, con un riesgo esperado de "</span></span>
<span id="annotated-cell-9-26"><a href="#annotated-cell-9-26" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="sc">{</span>descomposicion[entregado][<span class="dv">2</span>]<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="annotated-cell-9-27"><a href="#annotated-cell-9-27" aria-hidden="true" tabindex="-1"></a></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-9" data-target-annotation="2" onclick="event.preventDefault();">2</a><span id="annotated-cell-9-28" class="code-annotation-target"><a href="#annotated-cell-9-28" aria-hidden="true" tabindex="-1"></a>reparto <span class="op">=</span> {}</span>
<span id="annotated-cell-9-29"><a href="#annotated-cell-9-29" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> semilla <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">40</span>):</span>
<span id="annotated-cell-9-30"><a href="#annotated-cell-9-30" aria-hidden="true" tabindex="-1"></a>    otra <span class="op">=</span> {grado: np.array(cv_riesgo(grado, x, y, semilla<span class="op">=</span>semilla)[<span class="dv">1</span>])</span>
<span id="annotated-cell-9-31"><a href="#annotated-cell-9-31" aria-hidden="true" tabindex="-1"></a>            <span class="cf">for</span> grado <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">10</span>)}</span>
<span id="annotated-cell-9-32"><a href="#annotated-cell-9-32" aria-hidden="true" tabindex="-1"></a>    elegido <span class="op">=</span> regla_un_error_tipico(otra)[<span class="dv">1</span>]</span>
<span id="annotated-cell-9-33"><a href="#annotated-cell-9-33" aria-hidden="true" tabindex="-1"></a>    reparto[elegido] <span class="op">=</span> reparto.get(elegido, <span class="dv">0</span>) <span class="op">+</span> <span class="dv">1</span></span>
<span id="annotated-cell-9-34"><a href="#annotated-cell-9-34" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"con 40 particiones distintas, la regla entrega:"</span>,</span>
<span id="annotated-cell-9-35"><a href="#annotated-cell-9-35" aria-hidden="true" tabindex="-1"></a>      <span class="bu">dict</span>(<span class="bu">sorted</span>(reparto.items())))</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-9" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-9" data-code-lines="6" data-code-annotation="1">Los tres pasos de <a href="04-evaluacion.html#sec-comparar" class="quarto-xref"><span>Sección 4.4.3</span></a> en una función: el campeón es el candidato con la estimación de validación cruzada más baja, y de los más simples que él se entrega el primero cuya desventaja no llegue a un error típico.</span>
</dd>
<dt data-target-cell="annotated-cell-9" data-target-annotation="2">2</dt>
<dd>
<span data-code-cell="annotated-cell-9" data-code-lines="28" data-code-annotation="2">La misma regla sobre las mismas treinta y seis observaciones, cambiando solo cómo se reparten en bloques.</span>
</dd>
</dl>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>campeón: grado 8
 grado   diferencia   error típico   cociente
     0      +0.4475         0.0790       5.66
     1      +0.1479         0.0267       5.53
     2      +0.1688         0.0342       4.93
     3      +0.0022         0.0045       0.48
     4      +0.0037         0.0035       1.05
     5      +0.0002         0.0044       0.04
     6      +0.0025         0.0047       0.54
     7      +0.0023         0.0042       0.54

grado entregado: 3, con un riesgo esperado de 0.0512
con 40 particiones distintas, la regla entrega: {3: 27, 4: 10, 5: 1, 6: 1, 8: 1}</code></pre>
</div>
</div>
<p>El campeón es el grado 8, y cuatro candidatos más simples quedan a menos de un error típico de él. La regla se queda con el más simple de los cuatro, el grado 3, con un cociente de <span class="math inline">\(0.48\)</span>, y ese es también el que minimiza el riesgo esperado, <span class="math inline">\(0.0512\)</span>: recupera el mejor candidato y evita los <span class="math inline">\(0.4239\)</span> del campeón.</p>
<p>Conviene no leer eso como una garantía. La regla de un error típico es una heurística, y no hay ningún resultado que asegure que el candidato que devuelve minimice el riesgo esperado. El último bloque de la salida lo mide sobre estas mismas treinta y seis observaciones, cambiando solo la partición en bloques: en 27 de las 40 particiones la regla entrega el grado 3, en 10 el grado 4, cuyo riesgo esperado es <span class="math inline">\(0.0563\)</span> frente a <span class="math inline">\(0.0512\)</span>, y en las 3 restantes un grado más alto.</p>
<p>Lo que la regla cambia es la pregunta que decide. El mínimo de la curva de validación pregunta cuál es el número más bajo, y por <a href="04-evaluacion.html#prp-minimo-sesgado" class="quarto-xref">Proposición&nbsp;<span>4.3</span></a> ese número cae donde lo lleve el ruido. La regla pregunta cuál es el candidato más simple cuya desventaja frente al campeón no se “distingue del ruido”, y esa pregunta se contesta con la diferencia emparejada de <a href="04-evaluacion.html#def-diferencia-emparejada" class="quarto-xref">Definición&nbsp;<span>4.6</span></a>, que cancela la dificultad común de los bloques y mide mucho mejor la comparación que la propia columna <code>ee</code>.</p>
<div class="cajanegra">
<p><strong>El doble descenso queda fuera.</strong> Con clases de hipótesis muy grandes, del orden del número de observaciones o mayores, la curva en U deja de ser una U: el riesgo vuelve a bajar pasado el punto en que el modelo interpola los datos. El fenómeno se llama doble descenso, es importante para entender modelos con millones de parámetros y no es evaluable en este curso, porque exige herramientas que no vamos a ver.</p>
</div>
</section>
<section id="caso-práctico-la-curva-en-u-en-los-datos-de-madrid" class="level2">
<h2 class="anchored" data-anchor-id="caso-práctico-la-curva-en-u-en-los-datos-de-madrid">Caso práctico: la curva en U en los datos de Madrid</h2>
<p>Volvamos a los anuncios del capítulo 5, con el mismo reparto por anfitrión y el mismo protocolo. El punto de partida es el modelo que aquel capítulo entregó: recorte al percentil 99, imputación por la mediana con indicadora, estandarización, tipo de habitación y barrio agrupado, y un <span class="math inline">\(\mathrm{RMSE}\)</span> de <span class="math inline">\(82.39\)</span> euros en test. La pregunta que intentaremos resolver es si una clase de hipótesis más rica lo mejora.</p>
<p>Vamos a subir el grado del polinomio y estudiar qué le sucede al riesgo. Las variables que se van a aumentar son las cuatro continuas de tamaño, <code>accommodates</code>, <code>bathrooms</code>, <code>bedrooms</code> y <code>beds</code>, y lo único que cambia de un candidato a otro es el grado.</p>
<div id="12ea24bb" class="cell" data-execution_count="17">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.compose <span class="im">import</span> ColumnTransformer</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.impute <span class="im">import</span> MissingIndicator, SimpleImputer</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LinearRegression</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> GroupKFold, GroupShuffleSplit</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.pipeline <span class="im">import</span> Pipeline</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.base <span class="im">import</span> BaseEstimator, TransformerMixin</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> (OneHotEncoder, PolynomialFeatures,</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>                                   StandardScaler)</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>warnings.simplefilter(<span class="st">"ignore"</span>)</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>anuncios <span class="op">=</span> pd.read_csv(<span class="st">"../datos/airbnb_madrid.csv"</span>)</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>NUMERICAS <span class="op">=</span> [<span class="st">"accommodates"</span>, <span class="st">"bathrooms"</span>, <span class="st">"bedrooms"</span>, <span class="st">"beds"</span>,</span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>             <span class="st">"minimum_nights"</span>, <span class="st">"number_of_reviews"</span>,</span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a>             <span class="st">"review_scores_rating"</span>, <span class="st">"availability_365"</span>]</span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a>CATEGORICAS <span class="op">=</span> [<span class="st">"room_type"</span>, <span class="st">"neighbourhood_cleansed"</span>]</span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a>TAMANO <span class="op">=</span> [<span class="st">"accommodates"</span>, <span class="st">"bathrooms"</span>, <span class="st">"bedrooms"</span>, <span class="st">"beds"</span>]</span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a>RESTO <span class="op">=</span> [c <span class="cf">for</span> c <span class="kw">in</span> NUMERICAS <span class="cf">if</span> c <span class="kw">not</span> <span class="kw">in</span> TAMANO]</span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a>indices_train, indices_test <span class="op">=</span> <span class="bu">next</span>(</span>
<span id="cb20-25"><a href="#cb20-25" aria-hidden="true" tabindex="-1"></a>    GroupShuffleSplit(n_splits<span class="op">=</span><span class="dv">1</span>, test_size<span class="op">=</span><span class="fl">0.25</span>, random_state<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb20-26"><a href="#cb20-26" aria-hidden="true" tabindex="-1"></a>    .split(anuncios, groups<span class="op">=</span>anuncios[<span class="st">"host_id"</span>]))</span>
<span id="cb20-27"><a href="#cb20-27" aria-hidden="true" tabindex="-1"></a>train_a <span class="op">=</span> anuncios.iloc[indices_train]</span>
<span id="cb20-28"><a href="#cb20-28" aria-hidden="true" tabindex="-1"></a>test_a <span class="op">=</span> anuncios.iloc[indices_test]</span>
<span id="cb20-29"><a href="#cb20-29" aria-hidden="true" tabindex="-1"></a>y_train_a <span class="op">=</span> train_a[<span class="st">"price"</span>].to_numpy()</span>
<span id="cb20-30"><a href="#cb20-30" aria-hidden="true" tabindex="-1"></a>y_test_a <span class="op">=</span> test_a[<span class="st">"price"</span>].to_numpy()</span>
<span id="cb20-31"><a href="#cb20-31" aria-hidden="true" tabindex="-1"></a>grupos_a <span class="op">=</span> train_a[<span class="st">"host_id"</span>].to_numpy()</span>
<span id="cb20-32"><a href="#cb20-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-33"><a href="#cb20-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-34"><a href="#cb20-34" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> mse(y_pred, y):</span>
<span id="cb20-35"><a href="#cb20-35" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="bu">float</span>(np.mean((np.asarray(y_pred) <span class="op">-</span> np.asarray(y)) <span class="op">**</span> <span class="dv">2</span>))</span>
<span id="cb20-36"><a href="#cb20-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-37"><a href="#cb20-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-38"><a href="#cb20-38" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"train </span><span class="sc">{</span><span class="bu">len</span>(train_a)<span class="sc">}</span><span class="ss"> anuncios, test </span><span class="sc">{</span><span class="bu">len</span>(test_a)<span class="sc">}</span><span class="ss"> anuncios"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>train 11216 anuncios, test 3784 anuncios</code></pre>
</div>
</div>
<div id="4b5b770b" class="cell" data-execution_count="18">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="annotated-cell-11"><pre class="sourceCode python code-annotation-code code-with-copy code-annotated"><code class="sourceCode python"><a class="code-annotation-anchor" data-target-cell="annotated-cell-11" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-11-1" class="code-annotation-target"><a href="#annotated-cell-11-1" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> Recortador(BaseEstimator, TransformerMixin):</span>
<span id="annotated-cell-11-2"><a href="#annotated-cell-11-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Recorta cada columna al percentil 99 estimado en fit."""</span></span>
<span id="annotated-cell-11-3"><a href="#annotated-cell-11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-11-4"><a href="#annotated-cell-11-4" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> fit(<span class="va">self</span>, X, y<span class="op">=</span><span class="va">None</span>):</span>
<span id="annotated-cell-11-5"><a href="#annotated-cell-11-5" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.limites_ <span class="op">=</span> np.nanquantile(np.asarray(X, dtype<span class="op">=</span><span class="bu">float</span>),</span>
<span id="annotated-cell-11-6"><a href="#annotated-cell-11-6" aria-hidden="true" tabindex="-1"></a>                                       <span class="fl">0.99</span>, axis<span class="op">=</span><span class="dv">0</span>)</span>
<span id="annotated-cell-11-7"><a href="#annotated-cell-11-7" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="va">self</span></span>
<span id="annotated-cell-11-8"><a href="#annotated-cell-11-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-11-9"><a href="#annotated-cell-11-9" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> transform(<span class="va">self</span>, X):</span>
<span id="annotated-cell-11-10"><a href="#annotated-cell-11-10" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> np.minimum(np.asarray(X, dtype<span class="op">=</span><span class="bu">float</span>), <span class="va">self</span>.limites_)</span>
<span id="annotated-cell-11-11"><a href="#annotated-cell-11-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-11-12"><a href="#annotated-cell-11-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-11-13"><a href="#annotated-cell-11-13" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> codificador():</span>
<span id="annotated-cell-11-14"><a href="#annotated-cell-11-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> OneHotEncoder(drop<span class="op">=</span><span class="st">"first"</span>, min_frequency<span class="op">=</span><span class="dv">30</span>,</span>
<span id="annotated-cell-11-15"><a href="#annotated-cell-11-15" aria-hidden="true" tabindex="-1"></a>                         handle_unknown<span class="op">=</span><span class="st">"infrequent_if_exist"</span>,</span>
<span id="annotated-cell-11-16"><a href="#annotated-cell-11-16" aria-hidden="true" tabindex="-1"></a>                         sparse_output<span class="op">=</span><span class="va">False</span>)</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-11" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-11" data-code-lines="1" data-code-annotation="1">Las dos piezas son las del capítulo 5, repetidas aquí para que el cuaderno sea autónomo: el recortador y el codificador con <code>min_frequency=30</code>.</span>
</dd>
</dl>
</div>
</div>
<p>Para medir el efecto de la complejidad sin cambiar nada más, una única función construye el <em>pipeline</em> completo a partir del grado que se le pide.</p>
<div id="fb50e5c2" class="cell" data-execution_count="19">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="annotated-cell-12"><pre class="sourceCode python code-annotation-code code-with-copy code-annotated"><code class="sourceCode python"><a class="code-annotation-anchor" data-target-cell="annotated-cell-12" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-12-1" class="code-annotation-target"><a href="#annotated-cell-12-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> pipeline_polinomio(grado, recorte<span class="op">=</span><span class="va">True</span>):</span>
<span id="annotated-cell-12-2"><a href="#annotated-cell-12-2" aria-hidden="true" tabindex="-1"></a>    tamano <span class="op">=</span> [(<span class="st">"recortar"</span>, Recortador())] <span class="cf">if</span> recorte <span class="cf">else</span> []</span>
<span id="annotated-cell-12-3"><a href="#annotated-cell-12-3" aria-hidden="true" tabindex="-1"></a>    tamano <span class="op">+=</span> [(<span class="st">"imputar"</span>, SimpleImputer(strategy<span class="op">=</span><span class="st">"median"</span>)),</span>
<span id="annotated-cell-12-4"><a href="#annotated-cell-12-4" aria-hidden="true" tabindex="-1"></a>               (<span class="st">"expandir"</span>, PolynomialFeatures(grado,</span>
<span id="annotated-cell-12-5"><a href="#annotated-cell-12-5" aria-hidden="true" tabindex="-1"></a>                                               include_bias<span class="op">=</span><span class="va">False</span>)),</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-12" data-target-annotation="2" onclick="event.preventDefault();">2</a><span id="annotated-cell-12-6" class="code-annotation-target"><a href="#annotated-cell-12-6" aria-hidden="true" tabindex="-1"></a>               (<span class="st">"escalar"</span>, StandardScaler())]</span>
<span id="annotated-cell-12-7"><a href="#annotated-cell-12-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-12-8"><a href="#annotated-cell-12-8" aria-hidden="true" tabindex="-1"></a>    otras <span class="op">=</span> [(<span class="st">"recortar"</span>, Recortador())] <span class="cf">if</span> recorte <span class="cf">else</span> []</span>
<span id="annotated-cell-12-9"><a href="#annotated-cell-12-9" aria-hidden="true" tabindex="-1"></a>    otras <span class="op">+=</span> [(<span class="st">"imputar"</span>, SimpleImputer(strategy<span class="op">=</span><span class="st">"median"</span>,</span>
<span id="annotated-cell-12-10"><a href="#annotated-cell-12-10" aria-hidden="true" tabindex="-1"></a>                                        add_indicator<span class="op">=</span><span class="va">True</span>)),</span>
<span id="annotated-cell-12-11"><a href="#annotated-cell-12-11" aria-hidden="true" tabindex="-1"></a>              (<span class="st">"escalar"</span>, StandardScaler())]</span>
<span id="annotated-cell-12-12"><a href="#annotated-cell-12-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-12-13"><a href="#annotated-cell-12-13" aria-hidden="true" tabindex="-1"></a>    preparar <span class="op">=</span> ColumnTransformer([</span>
<span id="annotated-cell-12-14"><a href="#annotated-cell-12-14" aria-hidden="true" tabindex="-1"></a>        (<span class="st">"tam"</span>, Pipeline(tamano), TAMANO),</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-12" data-target-annotation="3" onclick="event.preventDefault();">3</a><span id="annotated-cell-12-15" class="code-annotation-target"><a href="#annotated-cell-12-15" aria-hidden="true" tabindex="-1"></a>        (<span class="st">"faltan"</span>, MissingIndicator(), TAMANO),</span>
<span id="annotated-cell-12-16"><a href="#annotated-cell-12-16" aria-hidden="true" tabindex="-1"></a>        (<span class="st">"otras"</span>, Pipeline(otras), RESTO),</span>
<span id="annotated-cell-12-17"><a href="#annotated-cell-12-17" aria-hidden="true" tabindex="-1"></a>        (<span class="st">"cat"</span>, codificador(), CATEGORICAS)])</span>
<span id="annotated-cell-12-18"><a href="#annotated-cell-12-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> Pipeline([(<span class="st">"preparar"</span>, preparar),</span>
<span id="annotated-cell-12-19"><a href="#annotated-cell-12-19" aria-hidden="true" tabindex="-1"></a>                     (<span class="st">"modelo"</span>, LinearRegression())])</span>
<span id="annotated-cell-12-20"><a href="#annotated-cell-12-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-12-21"><a href="#annotated-cell-12-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-12-22"><a href="#annotated-cell-12-22" aria-hidden="true" tabindex="-1"></a>candidatos <span class="op">=</span> {</span>
<span id="annotated-cell-12-23"><a href="#annotated-cell-12-23" aria-hidden="true" tabindex="-1"></a>    <span class="st">"grado 1 (capítulo 5)"</span>: pipeline_polinomio(<span class="dv">1</span>),</span>
<span id="annotated-cell-12-24"><a href="#annotated-cell-12-24" aria-hidden="true" tabindex="-1"></a>    <span class="st">"grado 2"</span>: pipeline_polinomio(<span class="dv">2</span>),</span>
<span id="annotated-cell-12-25"><a href="#annotated-cell-12-25" aria-hidden="true" tabindex="-1"></a>    <span class="st">"grado 4"</span>: pipeline_polinomio(<span class="dv">4</span>),</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-12" data-target-annotation="4" onclick="event.preventDefault();">4</a><span id="annotated-cell-12-26" class="code-annotation-target"><a href="#annotated-cell-12-26" aria-hidden="true" tabindex="-1"></a>    <span class="st">"grado 2 sin recortar"</span>: pipeline_polinomio(<span class="dv">2</span>, recorte<span class="op">=</span><span class="va">False</span>),</span>
<span id="annotated-cell-12-27"><a href="#annotated-cell-12-27" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="annotated-cell-12-28"><a href="#annotated-cell-12-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-12-29"><a href="#annotated-cell-12-29" aria-hidden="true" tabindex="-1"></a>particion <span class="op">=</span> GroupKFold(n_splits<span class="op">=</span><span class="dv">5</span>)</span>
<span id="annotated-cell-12-30"><a href="#annotated-cell-12-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-12-31"><a href="#annotated-cell-12-31" aria-hidden="true" tabindex="-1"></a>bloques_a <span class="op">=</span> {}</span>
<span id="annotated-cell-12-32"><a href="#annotated-cell-12-32" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> nombre, modelo <span class="kw">in</span> candidatos.items():</span>
<span id="annotated-cell-12-33"><a href="#annotated-cell-12-33" aria-hidden="true" tabindex="-1"></a>    riesgos <span class="op">=</span> []</span>
<span id="annotated-cell-12-34"><a href="#annotated-cell-12-34" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i_ajuste, i_val <span class="kw">in</span> particion.split(train_a, y_train_a,</span>
<span id="annotated-cell-12-35"><a href="#annotated-cell-12-35" aria-hidden="true" tabindex="-1"></a>                                           groups<span class="op">=</span>grupos_a):</span>
<span id="annotated-cell-12-36"><a href="#annotated-cell-12-36" aria-hidden="true" tabindex="-1"></a>        modelo.fit(train_a.iloc[i_ajuste], y_train_a[i_ajuste])</span>
<span id="annotated-cell-12-37"><a href="#annotated-cell-12-37" aria-hidden="true" tabindex="-1"></a>        riesgos.append(mse(modelo.predict(train_a.iloc[i_val]),</span>
<span id="annotated-cell-12-38"><a href="#annotated-cell-12-38" aria-hidden="true" tabindex="-1"></a>                           y_train_a[i_val]))</span>
<span id="annotated-cell-12-39"><a href="#annotated-cell-12-39" aria-hidden="true" tabindex="-1"></a>    bloques_a[nombre] <span class="op">=</span> np.array(riesgos)</span>
<span id="annotated-cell-12-40"><a href="#annotated-cell-12-40" aria-hidden="true" tabindex="-1"></a></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-12" data-target-annotation="5" onclick="event.preventDefault();">5</a><span id="annotated-cell-12-41" class="code-annotation-target"><a href="#annotated-cell-12-41" aria-hidden="true" tabindex="-1"></a>referencia <span class="op">=</span> bloques_a[<span class="st">"grado 1 (capítulo 5)"</span>]</span>
<span id="annotated-cell-12-42"><a href="#annotated-cell-12-42" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'candidato'</span><span class="sc">:24s}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'cols'</span><span class="sc">:&gt;5}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'CV(5)'</span><span class="sc">:&gt;9}</span><span class="ss"> "</span></span>
<span id="annotated-cell-12-43"><a href="#annotated-cell-12-43" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="sc">{</span><span class="st">'diferencia emparejada'</span><span class="sc">:&gt;24}</span><span class="ss">"</span>)</span>
<span id="annotated-cell-12-44"><a href="#annotated-cell-12-44" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> nombre, modelo <span class="kw">in</span> candidatos.items():</span>
<span id="annotated-cell-12-45"><a href="#annotated-cell-12-45" aria-hidden="true" tabindex="-1"></a>    columnas <span class="op">=</span> (modelo.fit(train_a, y_train_a)</span>
<span id="annotated-cell-12-46"><a href="#annotated-cell-12-46" aria-hidden="true" tabindex="-1"></a>                .named_steps[<span class="st">"preparar"</span>].transform(train_a).shape[<span class="dv">1</span>])</span>
<span id="annotated-cell-12-47"><a href="#annotated-cell-12-47" aria-hidden="true" tabindex="-1"></a>    r <span class="op">=</span> bloques_a[nombre]</span>
<span id="annotated-cell-12-48"><a href="#annotated-cell-12-48" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> nombre <span class="op">==</span> <span class="st">"grado 1 (capítulo 5)"</span>:</span>
<span id="annotated-cell-12-49"><a href="#annotated-cell-12-49" aria-hidden="true" tabindex="-1"></a>        resumen <span class="op">=</span> <span class="st">"referencia"</span></span>
<span id="annotated-cell-12-50"><a href="#annotated-cell-12-50" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="annotated-cell-12-51"><a href="#annotated-cell-12-51" aria-hidden="true" tabindex="-1"></a>        d <span class="op">=</span> r <span class="op">-</span> referencia</span>
<span id="annotated-cell-12-52"><a href="#annotated-cell-12-52" aria-hidden="true" tabindex="-1"></a>        ee <span class="op">=</span> d.std(ddof<span class="op">=</span><span class="dv">1</span>) <span class="op">/</span> np.sqrt(<span class="dv">5</span>)</span>
<span id="annotated-cell-12-53"><a href="#annotated-cell-12-53" aria-hidden="true" tabindex="-1"></a>        resumen <span class="op">=</span> <span class="ss">f"</span><span class="sc">{</span>d<span class="sc">.</span>mean()<span class="sc">:+.1f}</span><span class="ss"> ± </span><span class="sc">{</span>ee<span class="sc">:.1f}</span><span class="ss">"</span></span>
<span id="annotated-cell-12-54"><a href="#annotated-cell-12-54" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>nombre<span class="sc">:24s}</span><span class="ss"> </span><span class="sc">{</span>columnas<span class="sc">:5d}</span><span class="ss"> </span><span class="sc">{</span>r<span class="sc">.</span>mean()<span class="sc">:9.1f}</span><span class="ss"> </span><span class="sc">{</span>resumen<span class="sc">:&gt;24}</span><span class="ss">"</span>)</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-12" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-12" data-code-lines="1" data-code-annotation="1">Todos los candidatos pasan por la misma preparación y se diferencian solo en el grado, que es aquí el parámetro de complejidad. <code>PolynomialFeatures</code> es la herramienta encargada de generar esta complejidad geométrica: toma las variables originales y crea automáticamente nuevas columnas con sus potencias y productos cruzados hasta el grado indicado (por ejemplo, añadiendo el cuadrado del número de camas o multiplicando el número de baños por el de habitaciones). Con grado 1 el paso polinómico no hace nada, así que ese candidato es el modelo exacto que entregó el capítulo 5.</span>
</dd>
<dt data-target-cell="annotated-cell-12" data-target-annotation="2">2</dt>
<dd>
<span data-code-cell="annotated-cell-12" data-code-lines="6" data-code-annotation="2"><code>PolynomialFeatures</code> va después del imputador, porque si recibiera las indicadoras de ausencia elevaría al cuadrado columnas de ceros y unos, que son iguales a su cuadrado, y la matriz de diseño perdería rango. Y va antes del escalador, para que las columnas nuevas generadas (que pueden alcanzar valores enormes) entren en la misma escala que las demás.</span>
</dd>
<dt data-target-cell="annotated-cell-12" data-target-annotation="3">3</dt>
<dd>
<span data-code-cell="annotated-cell-12" data-code-lines="15" data-code-annotation="3">Por eso las indicadoras de las variables de tamaño se añaden en una rama aparte, que no pasa por el paso polinómico.</span>
</dd>
<dt data-target-cell="annotated-cell-12" data-target-annotation="4">4</dt>
<dd>
<span data-code-cell="annotated-cell-12" data-code-lines="26" data-code-annotation="4">El candidato de contraste: el mismo grado 2, pero sin el recorte al percentil 99 del capítulo 5.</span>
</dd>
<dt data-target-cell="annotated-cell-12" data-target-annotation="5">5</dt>
<dd>
<span data-code-cell="annotated-cell-12" data-code-lines="41" data-code-annotation="5">La comparación es la diferencia emparejada de <a href="04-evaluacion.html#def-diferencia-emparejada" class="quarto-xref">Definición&nbsp;<span>4.6</span></a>.</span>
</dd>
</dl>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>candidato                 cols     CV(5)    diferencia emparejada
grado 1 (capítulo 5)        88    7096.7               referencia
grado 2                     98    6904.6            -192.1 ± 65.5
grado 4                    153    7927.6           +830.9 ± 947.1
grado 2 sin recortar        98   10229.9         +3133.2 ± 1823.8</code></pre>
</div>
</div>
<p>La tabla dice tres cosas.</p>
<ol type="1">
<li><strong>Algo de flexibilidad baja el sesgo.</strong> El grado 2 añade diez columnas, cuatro cuadrados y seis productos entre pares de variables de tamaño, que son las interacciones de la sección segunda. El riesgo de validación baja <span class="math inline">\(192.1\pm65.5\)</span>, casi tres errores típicos: sobre <span class="math inline">\(7096.7\)</span> es una mejora del 3 %, y dice que el modelo lineal del capítulo 5 tenía algo de sesgo por resolver.</li>
<li><strong>Más flexibilidad se paga en la precisión de la medición.</strong> El grado 4 necesita 153 columnas y deja el riesgo en <span class="math inline">\(7927.6\)</span>, con una diferencia de <span class="math inline">\(+830.9\pm947.1\)</span>. El error típico emparejado se ha multiplicado por catorce respecto de la fila anterior, y con cinco bloques eso deja la comparación sin veredicto: no se puede afirmar que empeore, y tampoco hay ningún indicio de que mejore. La rama derecha de la curva en U no aparece aquí como un riesgo alto y claro, sino como una estimación que se vuelve demasiado imprecisa para decidir.</li>
<li><strong>La preparación de los datos y la clase de hipótesis no son decisiones independientes.</strong> El mismo grado 2, sin el recorte al percentil 99, deja el riesgo en <span class="math inline">\(10\,229.9\)</span>, un 44 % peor que la referencia. Elevar al cuadrado una columna que llega a 167 camas produce valores de otro orden de magnitud, y el ajuste se va detrás de ellos. Su error típico emparejado, <span class="math inline">\(1823.8\)</span>, es el mayor de la tabla: el candidato no es peor de forma estable, es inestable de un bloque a otro.</li>
</ol>
<div id="9553829a" class="cell" data-execution_count="20">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="annotated-cell-13"><pre class="sourceCode python code-annotation-code code-with-copy"><code class="sourceCode python"><span id="annotated-cell-13-1"><a href="#annotated-cell-13-1" aria-hidden="true" tabindex="-1"></a>elegido <span class="op">=</span> <span class="bu">min</span>(bloques_a, key<span class="op">=</span><span class="kw">lambda</span> k: bloques_a[k].mean())</span>
<span id="annotated-cell-13-2"><a href="#annotated-cell-13-2" aria-hidden="true" tabindex="-1"></a>final <span class="op">=</span> candidatos[elegido].fit(train_a, y_train_a)</span>
<span id="annotated-cell-13-3"><a href="#annotated-cell-13-3" aria-hidden="true" tabindex="-1"></a>base <span class="op">=</span> candidatos[<span class="st">"grado 1 (capítulo 5)"</span>].fit(train_a, y_train_a)</span>
<span id="annotated-cell-13-4"><a href="#annotated-cell-13-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-13-5"><a href="#annotated-cell-13-5" aria-hidden="true" tabindex="-1"></a>perdidas <span class="op">=</span> (final.predict(test_a) <span class="op">-</span> y_test_a) <span class="op">**</span> <span class="dv">2</span></span>
<span id="annotated-cell-13-6"><a href="#annotated-cell-13-6" aria-hidden="true" tabindex="-1"></a>perdidas_base <span class="op">=</span> (base.predict(test_a) <span class="op">-</span> y_test_a) <span class="op">**</span> <span class="dv">2</span></span>
<span id="annotated-cell-13-7"><a href="#annotated-cell-13-7" aria-hidden="true" tabindex="-1"></a>d <span class="op">=</span> perdidas <span class="op">-</span> perdidas_base</span>
<span id="annotated-cell-13-8"><a href="#annotated-cell-13-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-13-9"><a href="#annotated-cell-13-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"elegido por CV(5): </span><span class="sc">{</span>elegido<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="annotated-cell-13-10"><a href="#annotated-cell-13-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'riesgo en test'</span><span class="sc">:22s}</span><span class="ss"> </span><span class="sc">{</span>perdidas<span class="sc">.</span>mean()<span class="sc">:8.1f}</span><span class="ss"> ± "</span></span>
<span id="annotated-cell-13-11"><a href="#annotated-cell-13-11" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="sc">{</span>perdidas<span class="sc">.</span>std(ddof<span class="op">=</span><span class="dv">1</span>) <span class="op">/</span> np<span class="sc">.</span>sqrt(<span class="bu">len</span>(perdidas))<span class="sc">:5.1f}</span><span class="ss">"</span></span>
<span id="annotated-cell-13-12"><a href="#annotated-cell-13-12" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"   RMSE </span><span class="sc">{</span>np<span class="sc">.</span>sqrt(perdidas.mean())<span class="sc">:6.2f}</span><span class="ss"> euros"</span>)</span>
<span id="annotated-cell-13-13"><a href="#annotated-cell-13-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'el del capítulo 5'</span><span class="sc">:22s}</span><span class="ss"> </span><span class="sc">{</span>perdidas_base<span class="sc">.</span>mean()<span class="sc">:8.1f}</span><span class="ss"> ± "</span></span>
<span id="annotated-cell-13-14"><a href="#annotated-cell-13-14" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="sc">{</span>perdidas_base<span class="sc">.</span>std(ddof<span class="op">=</span><span class="dv">1</span>) <span class="op">/</span> np<span class="sc">.</span>sqrt(<span class="bu">len</span>(perdidas_base))<span class="sc">:5.1f}</span><span class="ss">"</span></span>
<span id="annotated-cell-13-15"><a href="#annotated-cell-13-15" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"   RMSE </span><span class="sc">{</span>np<span class="sc">.</span>sqrt(perdidas_base.mean())<span class="sc">:6.2f}</span><span class="ss"> euros"</span>)</span>
<span id="annotated-cell-13-16"><a href="#annotated-cell-13-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"diferencia emparejada: </span><span class="sc">{</span>d<span class="sc">.</span>mean()<span class="sc">:+.1f}</span><span class="ss"> ± "</span></span>
<span id="annotated-cell-13-17"><a href="#annotated-cell-13-17" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="sc">{</span>d<span class="sc">.</span>std(ddof<span class="op">=</span><span class="dv">1</span>) <span class="op">/</span> np<span class="sc">.</span>sqrt(<span class="bu">len</span>(d))<span class="sc">:.1f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>elegido por CV(5): grado 2
riesgo en test           6509.0 ± 569.8   RMSE  80.68 euros
el del capítulo 5        6788.6 ± 577.0   RMSE  82.39 euros
diferencia emparejada: -279.6 ± 64.5</code></pre>
</div>
</div>
<p>La validación cruzada elige el grado 2, y el test se abre una vez para medirlo. En esa misma apertura se mide también el modelo del capítulo 5, porque las dos predicciones caen sobre los mismos 3784 anuncios y eso permite comparar emparejando; ninguno de los dos candidatos se ha elegido mirando el test.</p>
<p>El elegido comete un <span class="math inline">\(\mathrm{RMSE}\)</span> de <span class="math inline">\(80.68\)</span> euros frente a los <span class="math inline">\(82.39\)</span> del capítulo 5. Son <span class="math inline">\(1.7\)</span> euros sobre una mediana de 124. Los dos modelos se evalúan sobre los mismos 3784 anuncios, así que se emparejan igual que en <a href="04-evaluacion.html#sec-comparar" class="quarto-xref"><span>Sección 4.4.3</span></a>, con la observación en lugar del bloque como unidad: la diferencia emparejada es <span class="math inline">\(-279.6\pm64.5\)</span>, más de cuatro errores típicos. El error típico del riesgo de cada modelo por separado, unos <span class="math inline">\(570\)</span>, no es el que corresponde. La mejora es pequeña y es real.</p>
<p>El balance del capítulo es el siguiente. Sabemos construir clases de hipótesis tan flexibles como queramos; hemos demostrado que el error se descompone en ruido, sesgo y varianza; y hemos comprobado cómo la varianza se dispara con la complejidad hasta arruinar el modelo. También hemos aprendido la regla de oro: más datos curan la varianza, pero no el sesgo. Por tanto, ante un resultado insuficiente, nuestro primer paso será siempre diagnosticar en qué rama de la curva en U nos encontramos.</p>
<p>Lo que aún nos falta es un mecanismo para conservar la flexibilidad sin pagar el altísimo precio de la varianza. Hasta ahora, nuestra única forma de estabilizar el algoritmo ha sido amputar características; es decir, retroceder a una clase de hipótesis más pequeña y rígida. El próximo capítulo introduce la gran alternativa a esta renuncia.</p>
</section>
<section id="ejercicios" class="level2">
<h2 class="anchored" data-anchor-id="ejercicios">Ejercicios</h2>
<div id="exr-base-local" class="theorem exercise">
<p><span class="theorem-title"><strong>Ejercicio 6.1 (Otra base de características)</strong></span> &nbsp;</p>
<div class="nuevo">
<p>Las potencias no son la única forma de construir características. Otra es colocar gaussianas sobre el recorrido de <span class="math inline">\(x\)</span>,</p>
<p><span class="math display">\[
\varphi_j(x)=\exp\Bigl(-\frac{(x-c_j)^2}{2h^2}\Bigr),
\]</span></p>
<p>con centros <span class="math inline">\(c_1,\ldots,c_{d}\)</span> repartidos por él y una anchura <span class="math inline">\(h\)</span> común.</p>
<ol type="a">
<li>Construye la matriz de características con ocho centros equiespaciados en <span class="math inline">\([0,2]\)</span> y <span class="math inline">\(h=0.25\)</span>, ajusta el modelo sobre las treinta y seis observaciones del capítulo y dibuja la curva junto a la señal.</li>
<li>Repite con <span class="math inline">\(h=0.6\)</span> y di cuál de los dos términos de <a href="#thm-descomposicion" class="quarto-xref">Teorema&nbsp;<span>6.1</span></a> que dependen del modelo crece. Repite después con <span class="math inline">\(h=0.05\)</span> y explica por qué con treinta y seis observaciones la descomposición no se puede leer; rehazla con <span class="math inline">\(n=300\)</span>.</li>
<li>Razona por qué <span class="math inline">\(h\)</span> es un parámetro de complejidad aunque el número de características no cambie.</li>
</ol>
</div>
</div>
<div id="exr-descomposicion-simulada" class="theorem exercise">
<p><span class="theorem-title"><strong>Ejercicio 6.2 (Comprobar la descomposición)</strong></span> El capítulo calcula los tres términos de <a href="#eq-descomposicion" class="quarto-xref">Ecuación&nbsp;<span>6.5</span></a> por separado y afirma que suman el riesgo esperado.</p>
<ol type="a">
<li><span class="nuevo">El capítulo comprueba la identidad con las mismas dos mil muestras en los dos caminos, y por eso los dos números coinciden hasta el último decimal. Explica por qué esa coincidencia es algebraica y no estadística, y qué comprobación haría falta para que fuera estadística.</span></li>
<li>Repite <span class="nuevo">la tabla</span> con doscientas repeticiones en lugar de dos mil y explica qué término se estima peor. <span class="nuevo">Estima la varianza del grado 9 con tres semillas distintas y di hasta qué cifra se puede leer.</span></li>
<li>Comprueba que el término de ruido no cambia al variar el grado, y di qué línea del código lo garantiza por construcción.</li>
</ol>
</div>
<div id="exr-cv-recupera-el-minimo" class="theorem exercise">
<p><span class="theorem-title"><strong>Ejercicio 6.3 (Cuántas observaciones necesita la validación cruzada)</strong></span> Con una muestra de <span class="nuevo">treinta y seis</span> observaciones, la validación cruzada del capítulo no distingue los grados 3 a 8 y su mínimo cae en el <span class="nuevo">8</span>.</p>
<ol type="a">
<li>Repite la tabla de validación cruzada con <span class="math inline">\(n=100\)</span> y con <span class="math inline">\(n=400\)</span> y anota en cada caso el grado del mínimo.</li>
<li>Compara en cada caso el error típico entre bloques con la diferencia entre el grado 3 y el grado 7 del riesgo esperado. Explica la relación con lo que observas en a.</li>
<li>Repite la tabla con <span class="math inline">\(n=30\)</span> y diez semillas distintas, y cuenta cuántas veces el mínimo cae en cada grado. Relaciona la dispersión con <a href="04-evaluacion.html#prp-minimo-sesgado" class="quarto-xref">Proposición&nbsp;<span>4.3</span></a>.</li>
</ol>
</div>
<div id="exr-interacciones-dirigidas" class="theorem exercise">
<p><span class="theorem-title"><strong>Ejercicio 6.4 (Elegir interacciones con un motivo)</strong></span> &nbsp;</p>
<div class="nuevo">
<p>El grado 2 del caso práctico cruza las variables de tamaño entre sí, pero no con las categóricas. La interacción de <a href="#fig-interaccion" class="quarto-xref">Figura&nbsp;<span>6.4</span></a>, la que hace que una plaza más valga distinto en una vivienda completa y en una habitación privada, no está en ninguno de los cuatro candidatos.</p>
<ol type="a">
<li>Añade un candidato que multiplique las cuatro variables de tamaño por las indicadoras del tipo de habitación, y mide su estimación por validación cruzada. El cruce tiene que ser un transformador dentro del <em>pipeline</em>, no una columna añadida a la tabla, para que sus medianas y sus percentiles se estimen en cada bloque: es la regla del capítulo 5.</li>
<li>Añade otro que cruce con el distrito en lugar de con el tipo de habitación, cuenta cuántas columnas produce y explica el resultado con la descomposición.</li>
<li>Un compañero propone probar todos los cruces posibles de una variable numérica por una categórica y quedarse con el mejor. Di qué objeción tiene ese plan y qué habría que hacer en su lugar.</li>
</ol>
</div>
</div>


</section>

<p><br><br><span style="color:grey;">© Roi Naveiro, CUNEF Universidad, 2026</span></p></main> <!-- /main -->
<!-- Sangrado de las lineas de codigo que se parten.

Con `code-overflow: wrap`, una linea mas larga que el bloque se parte en dos lineas
visuales. La continuacion tiene que quedar a la derecha del comienzo de la sentencia
que continua, y a que altura sea eso depende de la indentacion de esa linea, que CSS
no puede leer. Este script la lee de cada linea y fija su sangria francesa en
unidades `ch`, que en una fuente monoespaciada es exactamente un caracter: la
continuacion cae cuatro caracteres a la derecha del comienzo de su propia sentencia.

Sin JavaScript queda la sangria fija de `custom.scss`, que es el comportamiento
anterior. -->
<script>
(function () {
  var PASO = 4;      // caracteres que se sangra la continuacion
  var TOPE = 24;     // sangria maxima, para que en una columna estrecha quede sitio
  function sangra() {
    document.querySelectorAll("pre.sourceCode code > span").forEach(function (linea) {
      var blancos = /^[ \t]*/.exec(linea.textContent)[0].replace(/\t/g, "    ").length;
      var sangria = Math.min(blancos + PASO, TOPE) + "ch";
      linea.style.paddingLeft = sangria;
      linea.style.textIndent = "-" + sangria;
    });
  }
  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", sangra);
  } else {
    sangra();
  }
})();
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../capitulos/05-preparacion-datos.html" class="pagination-link" aria-label="Preparar datos sin contaminar la evaluación">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Preparar datos sin contaminar la evaluación</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../capitulos/07-regularizacion.html" class="pagination-link" aria-label="Regularización">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Regularización</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>